### ISSUE TITLE
Authentication with jsonwebtoken

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma2#102]
Wondering if this error is due to my code, or related to **Prisma2** / **Photon**. When I tried to get the `userId` using the correct `token`, like this:

```js
const jwt = require('jsonwebtoken')
const getUserId = ctx => {
  const Authorization = ctx.request.get('Authorization')
  if (Authorization) {
    const token = Authorization.replace('Bearer ', '')
    if (token !== 'null') {
      const { userId } = jwt.verify(token, process.env.APP_SECRET)
      return userId
    }
  }
}
```
...I got the following error:

```terminal
Error: Error in Photon: 
thread 'arbiter:d933104c-e92c-48d7-9a55-3f68479723da:actix-net-worker-1' panicked at 'object was empty', src/libcore/option.rs:1038:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: core::builders::utils::extract_record_finder
  10: <core::builders::one::OneBuilder<'f> as core::builders::BuilderExt>::build
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  12: <&mut I as core::iter::traits::iterator::Iterator>::next
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  14: core::builders::root::RootBuilder::build_query
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  16: <&mut I as core::iter::traits::iterator::Iterator>::next
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: core::builders::root::RootBuilder::build
  19: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle
  20: prisma::http_handler
  21: <F as actix_web::with::FnWith<T, R>>::call_with
  22: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll
  23: <actix_web::pipeline::PipelineState<S, H>>::poll
  24: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io
  25: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler
  26: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll
  27: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
  28: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
  29: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll
  30: <futures::future::chain::Chain<A, B, C>>::poll
  31: futures::task_impl::std::set
  32: <futures::task_impl::Spawn<T>>::poll_future_notify
  33: tokio_current_thread::CurrentRunner::set_spawn
  34: <tokio_current_thread::scheduler::Scheduler<U>>::tick
  35: <tokio_current_thread::Entered<'a, P>>::block_on
  36: <std::thread::local::LocalKey<T>>::with
  37: <std::thread::local::LocalKey<T>>::with
  38: <std::thread::local::LocalKey<T>>::with
  39: <std::thread::local::LocalKey<T>>::with
  40: tokio::runtime::current_thread::runtime::Runtime::block_on

    at PhotonFetcher.<anonymous> (/Users/xxx/Apps/app/node_modules/@generated/photon/index.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/xxx/Apps/app/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by auderer** [comment]
The code you posted is fine - the problem is related to Photon, not your `getUserId` function.

Can you share your code where you use this function?

**Comment by heymartinadams** [comment]
Thanks, @auderer.

```javascript
const getUserId = require('./utils')

const user = async (parent, args, ctx) =>
  await ctx.photon.users.findOne({
    where: { id: getUserId(ctx) }
  })

module.exports = user
```

**Comment by pantharshit00** [comment]
Hi,

Can you please check whether the record with that ID currently exists in the database. 

We currently throw an error if the record doesn't exist.

**Comment by heymartinadams** [comment]
Ah, thanks for that, @pantharshit00!

Before signing the `jwt` I called `user` but forgot to include `await`:

```javascript
const user = ctx.photon.users.findOne({
    where: { userAuthToken }
})
```

instead of 

```javascript
const user = await ctx.photon.users.findOne({
    where: { userAuthToken }
})
```

So later, when `jwt` was applied, it created an error:
```javascript
return {
    token: jwt.sign({ userId: user.id }, process.env.APP_SECRET)
}
```
