### ISSUE TITLE
npm run seed error

### ISSUE THREAD

**Issue by lasharela** [prisma/prisma2#1026]
After prisma2 init > typescript > Starter kit GraphQL API + Auth 
&&
npm run seed 

I'm getting this error:

```
npm run seed

> graphql-auth@1.0.0 seed /Users/lasharela/Dev/zPlast/prisma2-test
> node prisma/seed

(node:15672) UnhandledPromiseRejectionWarning: Error: 
Invalid `const user1 = await photon.users.create()` invocation in /Users/lasharela/Dev/zPlast/prisma2-test/prisma/seed.js:5:36

  1 const { Photon } = require('@prisma/photon')
  2 const photon = new Photon()
  3 
  4 async function main() {
→ 5   const user1 = await photon.users.create(

Reason: Error occurred during query execution:
ConnectorError(UniqueConstraintViolation { field_name: "User.email" })

    at PhotonFetcher.<anonymous> (/Users/lasharela/Dev/zPlast/prisma2-test/node_modules/@prisma/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/lasharela/Dev/zPlast/prisma2-test/node_modules/@prisma/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:15672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment]
We already seed your database in the bootstrapping(it is step 5).

So if you run the seed script again without emptying the database, it will use the same email addresses. Email is a unique field so it is throwing a uniqueconstraint violiation error which is expected.
