### ISSUE TITLE
[Introspection] Error in RPC: CoreError: Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1056]
`prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3307/AdventureWorks2014" > AdventureWorks2014.log` returned this in stderr:

(Yes, it is ok that these credentials are public - you can use the command to reproduce maybe)

```
Error: Error in RPC
 Request: {
  "id": 1,
  "jsonrpc": "2.0",
  "method": "introspect",
  "params": [
    {
      "url": "mysql://guest:relational@relational.fit.cvut.cz:3307/AdventureWorks2014"
    }
  ]
}
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 1000,
    "message": "CoreError: Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)",
    "data": {
      "message": "Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)",
      "backtrace": null
    }
  },
  "id": 1
}
CoreError: Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

Wrote failed-introspect-20191205234635.md with debugging information.
Please put that file into a gist and post it in Slack.
1. cat failed-introspect-20191205234635.md | pbcopy
2. Create a gist https://gist.github.com/new
```

I can connect to the exact same connection string using HeidiSQL just fine at the same time:
![image](https://user-images.githubusercontent.com/183673/70281284-f7fb0300-17ba-11ea-9746-3e0576920c14.png)

Other databases of this server work as well, e.g. `prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3306/Accidents" > Accidents.log 2> Accidents_stderr.log`

Context:
```
λ prisma2 -v
prisma2@2.0.0-alpha.414, binary version: a7b03466b4d18c4690a0dfff75efdef816c9cf6b
```

**Comment by janpio** [comment]
Found more connection strings where it does not work:

```
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3308/Airline" > Airline.log 2> Airline_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3309/Atherosclerosis" > Atherosclerosis.log 2> Atherosclerosis_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3310/AustralianFootball" > AustralianFootball.log 2> AustralianFootball_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3311/Basketball_men" > Basketball_men.log 2> Basketball_men_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3312/Basketball_women" > Basketball_women.log 2> Basketball_women_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3313/Bench" > Bench.log 2> Bench_stderr.log
prisma2 introspect --url="mysql://guest:relational@relational.fit.cvut.cz:3314/Bench2" > Bench2.log 2> Bench2_stderr.log
```

**Comment by janpio** [comment]
With `DEBUG=*`:

```
2019-12-05T23:14:02.654Z getos { platform: 'win32', libssl: undefined }
2019-12-05T23:14:02.661Z IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"url":"mysql://guest:relational@relational.fit.cvut.cz:3436/twitterfromsearch4_20101001"}]}
Error: Error: Error in RPC
 Request: {
  "id": 1,
  "jsonrpc": "2.0",
  "method": "introspect",
  "params": [
    {
      "url": "mysql://guest:relational@relational.fit.cvut.cz:3436/twitterfromsearch4_20101001"
    }
  ]
}
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 1000,
    "message": "CoreError: Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)",
    "data": {
      "message": "Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)",
      "backtrace": null
    }
  },
  "id": 1
}
CoreError: Error in connector: Error querying the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

Wrote failed-introspect-20191206001423.md with debugging information.
Please put that file into a gist and post it in Slack.
1. cat failed-introspect-20191206001423.md | pbcopy
2. Create a gist https://gist.github.com/new

    at Object.registerCallback (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:250046:40)
    at IntrospectionEngine.handleResponse (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:249934:42)
    at LineStream.byline_1.default.on.line (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:250015:26)
    at LineStream.emit (events.js:198:13)
    at LineStream.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:151:32)
    at LineStream.module.exports.6149.LineStream._pushBuffer (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:146130:23)
```

**Comment by tomhoule** [comment]
The problem here was that the engines would hang when the database wasn't reachable. We implemented a timeout with a nice user-facing error in https://github.com/prisma/prisma-engine/pull/271 - maybe this issue can be closed.

**Comment by janpio** [comment]
Ahem, I did indeed mess up the ports (or better: Google Spreadsheets did!) and did not double check the connection string. Shame on me...
