### ISSUE TITLE
[Introspection] "No id field defined!" should not panic and crash, but just output an error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1077]
Currently the panic "No id field defined!" stops further output or proper error messages:

```
Introspection failed: Introspected schema can't be parsed.
Error: Schema parsing
thread 'main' panicked at 'No id field defined!', src\libcore\option.rs:1190:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  12: rust_begin_unwind
             at src\libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  14: core::option::expect_failed
             at src\libcore/option.rs:1190
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  16: once_cell::imp::initialize_inner
  17: once_cell::imp::OnceCell<T>::initialize
  18: prisma_models::fields::Fields::id
  19: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::many_records_arguments
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  23: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::new
  24: query_core::schema_builder::query_schema_builder::QuerySchemaBuilder::new
  25: prisma::cli::CliCommand::execute
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
  27: tokio::runtime::global::with_thread_pool
  28: tokio::runtime::global::with_state
  29: tokio::runtime::spawner::Spawner::enter
  30: tokio::runtime::time::variant::with_default
  31: std::thread::local::LocalKey<T>::with
  32: prisma::main
  33: std::rt::lang_start::{{closure}}
  34: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:49
  35: std::panicking::try::do_call
             at src\libstd/panicking.rs:292
  36: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  37: std::panicking::try
             at src\libstd/panicking.rs:271
  38: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  39: std::rt::lang_start_internal
             at src\libstd/rt.rs:48
  40: main
  41: _tmainCRTStartup
  42: mainCRTStartup
  43: sqlite3GenerateConstraintChecks
  44: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at Object.<anonymous> (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:73330:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

https://github.com/prisma/introspection-engine-output/pull/5/files#diff-17a99e700e722aa314f06783857af1f4

That is a shame, because the error might have other interesting information that we want to look at right now. We should make this an error like all the others as well.

**Comment by janpio** [comment]
> That is a shame, because the error might have other interesting information that we want to look at right now. We should make this an error like all the others as well.

This is probably not the case, as the crash happens later in the process (see https://github.com/prisma/prisma2/issues/1138)

**Comment by janpio** [comment]
Validator could already catch this problem and provide a nice error message (in step 2), instead of letting this through to the Query Engine (in step 3, steps see https://github.com/prisma/prisma2/issues/1138#issuecomment-581858996).

**Comment by janpio** [comment]
Implemented, see https://github.com/prisma/prisma2/issues/1515#issuecomment-582474849

**Comment by janpio** [comment]
Might not actually be fixed, reopening to figure out.

**Comment by janpio** [comment]
I was misled, only _one_ variation of this - which was caused by the absence of all IDs in the generated datamodel - was meant here and that one indeed does not give a panic any more, but a crash.

The more widespread version of this panic, that is caused by the presence of `@@id` in the schema is still correctly throwing a panic and tracked at: https://github.com/prisma/prisma2/issues/1114
