### ISSUE TITLE
[Introspection] Panic "No id field defined!" / panic-no-id-field-defined = Panic "No id field defined!" (caused by @@id)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1114]
```

Introspection failed: Introspected schema can't be parsed.
Error: Schema parsing thread 'main' panicked at 'No id field defined!', src\libcore\option.rs:1190:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  12: rust_begin_unwind
             at src\libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  14: core::option::expect_failed
             at src\libcore/option.rs:1190
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  16: once_cell::imp::initialize_inner
  17: once_cell::imp::OnceCell<T>::initialize
  18: prisma_models::fields::Fields::id
  19: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::many_records_arguments
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  23: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::new
  24: query_core::schema_builder::query_schema_builder::QuerySchemaBuilder::new
  25: prisma::cli::CliCommand::execute
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
  27: tokio_executor::enter::Enter::block_on
  28: std::thread::local::LocalKey<T>::with
  29: tokio::runtime::threadpool::Runtime::block_on
  30: prisma::main
  31: std::rt::lang_start::{{closure}}
  32: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:49
  33: std::panicking::try::do_call
             at src\libstd/panicking.rs:292
  34: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  35: std::panicking::try
             at src\libstd/panicking.rs:271
  36: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  37: std::rt::lang_start_internal
             at src\libstd/rt.rs:48
  38: main
  39: _tmainCRTStartup
  40: mainCRTStartup
  41: sqlite3GenerateConstraintChecks
  42: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at Object.<anonymous> (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:70179:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:70074:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Probably caused by:

```
model PlaylistTrack {
  PlaylistId Playlist
  TrackId    Track

  @@id([PlaylistId, TrackId])
}
```

**Comment by janpio** [comment]
Collection of schemas where `@@id` was confirmed as the source of this problem (via replacing all `@@id` with `foo Int @id`):

https://github.com/prisma/introspection-engine-output/blob/master/mysql/Chinook.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql/drupal.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql/employees.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql/matomo.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql/modx.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql/wordpress.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Biodegradability.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/CORA.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/DCG.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Elti.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/FNHK.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Facebook.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/NCAA.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/PremierLeague.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Same_gen.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Simpsons.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Toxicology.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/UTube.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Walmart_2014.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Walmart.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/WebKP.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/classicmodels.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/ctu_datatype_benchmark.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/ftp.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/imdb_ijs.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/tpcds.log
https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/twitterfromsearch4_20101001.log
https://github.com/prisma/introspection-engine-output/blob/master/postgres/chinook.log
https://github.com/prisma/introspection-engine-output/blob/master/postgres/northwind.log
https://github.com/prisma/introspection-engine-output/blob/master/postgres/shakespeare.log

This is 99% of all `panic-no-id-field-defined` pattern.

**Comment by janpio** [comment]
First AUMFIDARR merges took care of that 🚀
