### ISSUE TITLE
Engine has already been stopped

### ISSUE THREAD

**Issue by iherger** [prisma/prisma2#113]
Every once in a while, I get the following error message in my graphql-yoga server: 
```
Error: Error in Photon:
Engine has already been stopped
    at PhotonFetcher.<anonymous> (/Users/.../node_modules/@generated/photon/index.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/.../node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
Restarting the graphql-yoga server solves the problem.

**Comment by pantharshit00** [comment]
Can you provide us with a minimal reproduction? The provided information isn't sufficient for triaging this issue.

**Comment by iherger** [comment]
This has stopped. I will report back if it occurs again, and will then try to reproduce.

**Comment by timsuchanek** [comment]
@iherger are you using any watch command to reload your yoga server?

**Comment by iherger** [comment]
@timsuchanek , yes, I am using 
```
    "dev": "ts-node-dev -r dotenv/config --no-notify --respawn --transpileOnly ./src",
````

**Comment by aarshaw** [comment]
Using `now dev` and `now` - happening both locally and on now.sh - not using `graphql-yoga` so most likely not an issue to do with that specifically - regenerating the photon client seems to work for me, but inconsistently

**Comment by gihrig** [comment]
I am working on [photonjs graphql-auth TS example](https://github.com/prisma/photonjs/tree/master/examples/typescript/graphql-auth). I'm running the server with ts-node-dev

```json
"dev": "ts-node-dev --no-notify --respawn --transpileOnly ./src",
```

For me, the error only happens after another error, typically caused by `findOne` encountering no result and throwing

```error
Error: Error in Photon: 
ConnectorError(RecordDoesNotExist)
    at Object.<anonymous> (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/src/resolvers/Mutation.ts:56:17)
    at step (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/src/resolvers/Mutation.ts:32:23)
    at Object.throw (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/src/resolvers/Mutation.ts:13:53)
    at rejected (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/src/resolvers/Mutation.ts:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

As mentioned in the OP, this error is intermittent. I can execute the code that throws `RecordDoesNotExist` 25 times and `Engine has already been stopped` does not occur. When it does occur, it's typically no more that 3 - 5 other errors into the server session. I am not able to reproduce `Engine has already been stopped` on demand.

**Comment by gihrig** [comment]
### Reproduction of "Engine has already been stopped" Photonjs prisma/prisma2#113

I have been working on Photon's `typescript/graphql-auth` example, working around errors and generally making the example ready for use as a boilerplate for new projects. I run into this error periodically and have determined how to reliably reproduce it.

>Note: This error is triggered by invalid graphql input. With proper server-side input validation, this error should never occur.

>Note: The 'official' Photon [typescript/graphql-auth example](https://github.com/prisma/photonjs/tree/master/examples/typescript/graphql-auth) _does not_ demonstrate this error.

My system:

>macOS: 10.14.6
>prisma2: prisma2@2.0.0-preview-2, binary version: 4f33077038a490e4b2c1c260f109309e4a447181
>node: 12.5.0
>yarn: 1.16.0


### 1. Clone the repo, install dependencies and start the server:

>git clone -b engine-stopped https://github.com/gihrig/hello-photon-graphql-auth.git
>cd hello-photon-graphql-auth
>yarn
>yarn dev
>Open playground at http://localhost:4000/

### 2. Execute the `signup` mutation to confirm the server is working.

```graphql
mutation {
  signup(
      name: "Thomas"
      email: "thomas@prisma.io"
      password: "graphql"
  ) {
    token
  }
}
```

This should work as expected

### 3. Execute the `signup` mutation again, but with a missing `email` key

```graphql
mutation {
  signup(
      name: "Angie"
      password: "graphql"
  ) {
    token
  }
}
```

This throws an error as expected, and apparently, crashes the 'engine'.

<details>
 <summary>Console output</summary>

```
Error: 
Invalid `ctx.photon.users.create()` invocation in /Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/src/resolvers/Mutation.ts:19:45

15 resolve: async (parent,[object Object], ,[object Object], name,[object Object], email,[object Object], password ,[object Object],[object Object], ctx) => {
16   // User must not exist
17   // See permissions
18   const hashedPassword = await hash(password, 10)
19   const user = await ctx.photon.users.create({
       data: {
         name: 'Angie',
     +   email: String,
         password: '$2b$10$S141uyWaOXDB0VEBUuC5dO.rsIWkdI9pa0lhKr/95TiXqiBstWQwu',
     ?   id?: ID,
     ?   posts?: {
     ?     create?: PostCreateWithoutAuthorInput,
     ?     connect?: PostWhereUniqueInput
     ?   }
       }
     })

Argument email for data.email is missing.

Note: Lines with + are required, lines with ? are optional.

    at Document.validate (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/runtime/index.js:1476:23)
    at UserClient.get document [as document] (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:268:22)
    at UserClient.then (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:290:61)
```
</details>

### 4. Correct the mutation and run again

```graphql
mutation {
  signup(
      name: "Angie"
      email: "angie@prisma.io"
      password: "graphql"
  ) {
    token
  }
}
```

Even though the mutation is now correct, an error is thrown suggesting the server has shut down.

```
Error: Error in Photon: 
{
  "name": "RequestError",
  "code": "ECONNREFUSED",
  "host": "localhost:55999",
  ...
```

<details>
 <summary>full error</summary>

```
Error: Error in Photon: 
{
  "name": "RequestError",
  "code": "ECONNREFUSED",
  "host": "localhost:55999",
  "hostname": "localhost",
  "method": "POST",
  "path": "/",
  "protocol": "http:",
  "url": "http://localhost:55999/",
  "gotOptions": {
    "path": "/",
    "protocol": "http:",
    "slashes": true,
    "auth": null,
    "host": "localhost:55999",
    "port": "55999",
    "hostname": "localhost",
    "hash": null,
    "search": null,
    "query": null,
    "pathname": "/",
    "href": "http://localhost:55999/",
    "retry": {
      "methods": {},
      "statusCodes": {},
      "errorCodes": {}
    },
    "headers": {
      "user-agent": "got/9.6.0 (https://github.com/sindresorhus/got)",
      "content-type": "application/json",
      "accept": "application/json",
      "accept-encoding": "gzip, deflate",
      "content-length": 274
    },
    "hooks": {
      "beforeRequest": [],
      "beforeRedirect": [],
      "beforeRetry": [],
      "afterResponse": [],
      "beforeError": [],
      "init": []
    },
    "decompress": true,
    "throwHttpErrors": true,
    "followRedirect": true,
    "stream": false,
    "form": false,
    "json": true,
    "cache": false,
    "useElectronNet": false,
    "body": "{\"query\":\"mutation {\\n  createOneUser(data: {\\n    name: \\\"Angie\\\"\\n    email: \\\"angie@preisma.io\\\"\\n    password: \\\"$2b$10$cG/LyfnNyjWeHyG6B2aSHeOjkXso.hTEaIKsm9kGpXqeGjE2wQ9zK\\\"\\n  }) {\\n    id\\n    email\\n    password\\n    name\\n  }\\n}\",\"variables\":{},\"operationName\":\"\"}",
    "method": "POST",
    "forceRefresh": true
  }
}
    at PhotonFetcher.<anonymous> (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:34:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```
</details>

### 5. Run the correct mutation one more time to produce "Engine has already been stopped".

```graphql
mutation {
  signup(
      name: "Angie"
      email: "angie@prisma.io"
      password: "graphql"
  ) {
    token
  }
}
```

```
Error: Error in Photon: 
Engine has already been stopped
    at PhotonFetcher.<anonymous> (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:34:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/@generated/photon/index.js:5:65)
```

**Comment by pantharshit00** [comment]
I can confirm this. Appears to be a bug in nexus prisma where it is calling .disconnect() when the server throws any error.
