### ISSUE TITLE
Error: Cannot read property 'file' of undefined when running using lift

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma2#1154]
When trying to use lift like this: `prisma2 lift save` or `prisma2 lift up` I sometimes get the error: `Error: Cannot read property 'file' of undefined` Not sure what's the reason

I am using macOS

**Comment by pantharshit00** [comment]
I am unable to reproduce this on a minimal setup. Can you please tell me the size of your schema and the datasource that you are using. Maybe this is occurring on a schema with a significant amount of models.

Also, maybe try to reproduce this with debug mode enabled with `export DEBUG=*` and pasting the output here.

**Comment by BjoernRave** [comment]
Can't reproduc anymore, I think it was a problem with my local prisma2 installation, where for some reason it was using an older version

**Comment by FinnFrotscher** [comment]
+1 same issue
```
yarn run v1.22.4
$ source .env.database && prisma migrate up --experimental --schema src/services/prisma/schema.prisma
  prisma Environment variables not loaded (--schema was provided) +0ms
Error: TypeError: Cannot read property 'file' of undefined
    at /Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2938453
    at Array.map (<anonymous>)
    at Migrate.getLocalMigrations (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2938154)
    at async Migrate.getMigrationsToApply (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2939488)
    at async Migrate.up (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2933915)
    at async MigrateUp.parse (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:1866594)
    at async main (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:1480086)
error Command failed with exit code 1.
```

**Comment by janpio** [comment]
Can you please open a new issue @FinnFrotscher and include your `prisma -v` output?
Thanks.

**Comment by FinnFrotscher** [comment]
done @janpio 
https://github.com/prisma/prisma/issues/3595
