### ISSUE TITLE
Error when trying to filter multiple fields of a many-to-many relationship within a where clause

### ISSUE THREAD

**Issue by j-gajewski** [prisma/prisma2#1158]
I received the following error when I tried to query something with a nested where clause in GraphQL. The error seems to occurr only when trying to filter multiple fields of a many-to-many relationship within a nested where clause.

```
{
  "errors": [
    {
      "message": "\nInvalid `photon.()` invocation in /api/cimlibs/node_modules/nexus-prisma/dist/builder.js:129:97\n\n\n\nReason: Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1054, message: \"Unknown column \\'j0.id\\' in \\'IN/ALL/ANY subquery\\'\", state: \"42S22\" })\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new\n   1: failure::backtrace::Backtrace::new\n   2: quaint::connector::mysql::error::<impl core::convert::From<mysql_async::error::Error> for quaint::error::Error>::from\n   3: <std::future::GenFuture<T> as core::future::future::Future>::poll\n   4: <std::future::GenFuture<T> as core::future::future::Future>::poll\n   5: <std::future::GenFuture<T> as core::future::future::Future>::poll\n   6: std::future::poll_with_tls_context\n   7: <std::future::GenFuture<T> as core::future::future::Future>::poll\n   8: <std::future::GenFuture<T> as core::future::future::Future>::poll\n   9: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  11: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  12: std::future::poll_with_tls_context\n  13: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  14: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  15: std::panicking::try::do_call\n  16: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:80\n  17: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  18: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  19: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch\n  20: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll\n  21: tokio::task::core::Core<T>::poll\n  22: std::panicking::try::do_call\n  23: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:80\n  24: tokio::task::harness::Harness<T,S>::poll\n  25: tokio::runtime::thread_pool::worker::GenerationGuard::run_task\n  26: tokio::runtime::thread_pool::worker::GenerationGuard::run\n  27: std::thread::local::LocalKey<T>::with\n  28: std::thread::local::LocalKey<T>::with\n  29: tokio::runtime::thread_pool::worker::Worker::run\n  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n  31: std::panicking::try::do_call\n  32: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:80\n  33: tokio::task::harness::Harness<T,S>::poll\n  34: tokio::runtime::blocking::pool::Inner::run2\n  35: tokio::runtime::spawner::Spawner::enter\n  36: tokio::runtime::time::variant::with_default\n  37: tokio::runtime::blocking::pool::Inner::run\n  38: std::sys_common::backtrace::__rust_begin_short_backtrace\n  39: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:80\n  40: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922\n  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922\n      std::sys_common::thread::start_thread\n             at src/libstd/sys_common/thread.rs:13\n      std::sys::unix::thread::Thread::new::thread_start\n             at src/libstd/sys/unix/thread.rs:79\n  43: start_thread\n  44: clone\n) })\n",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "customers"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: ",
            "Invalid `photon.()` invocation in /api/cimlibs/node_modules/nexus-prisma/dist/builder.js:129:97",
            "",
            "",
            "",
            "Reason: Error occurred during query execution:",
            "ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1054, message: \"Unknown column \\'j0.id\\' in \\'IN/ALL/ANY subquery\\'\", state: \"42S22\" })",
            "",
            "stack backtrace:",
            "   0: failure::backtrace::internal::InternalBacktrace::new",
            "   1: failure::backtrace::Backtrace::new",
            "   2: quaint::connector::mysql::error::<impl core::convert::From<mysql_async::error::Error> for quaint::error::Error>::from",
            "   3: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "   4: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "   5: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "   6: std::future::poll_with_tls_context",
            "   7: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "   8: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "   9: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  10: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  11: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  12: std::future::poll_with_tls_context",
            "  13: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  14: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  15: std::panicking::try::do_call",
            "  16: __rust_maybe_catch_panic",
            "             at src/libpanic_unwind/lib.rs:80",
            "  17: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  18: <std::future::GenFuture<T> as core::future::future::Future>::poll",
            "  19: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch",
            "  20: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll",
            "  21: tokio::task::core::Core<T>::poll",
            "  22: std::panicking::try::do_call",
            "  23: __rust_maybe_catch_panic",
            "             at src/libpanic_unwind/lib.rs:80",
            "  24: tokio::task::harness::Harness<T,S>::poll",
            "  25: tokio::runtime::thread_pool::worker::GenerationGuard::run_task",
            "  26: tokio::runtime::thread_pool::worker::GenerationGuard::run",
            "  27: std::thread::local::LocalKey<T>::with",
            "  28: std::thread::local::LocalKey<T>::with",
            "  29: tokio::runtime::thread_pool::worker::Worker::run",
            "  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once",
            "  31: std::panicking::try::do_call",
            "  32: __rust_maybe_catch_panic",
            "             at src/libpanic_unwind/lib.rs:80",
            "  33: tokio::task::harness::Harness<T,S>::poll",
            "  34: tokio::runtime::blocking::pool::Inner::run2",
            "  35: tokio::runtime::spawner::Spawner::enter",
            "  36: tokio::runtime::time::variant::with_default",
            "  37: tokio::runtime::blocking::pool::Inner::run",
            "  38: std::sys_common::backtrace::__rust_begin_short_backtrace",
            "  39: __rust_maybe_catch_panic",
            "             at src/libpanic_unwind/lib.rs:80",
            "  40: core::ops::function::FnOnce::call_once{{vtable.shim}}",
            "  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once",
            "             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922",
            "  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once",
            "             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922",
            "      std::sys_common::thread::start_thread",
            "             at src/libstd/sys_common/thread.rs:13",
            "      std::sys::unix::thread::Thread::new::thread_start",
            "             at src/libstd/sys/unix/thread.rs:79",
            "  43: start_thread",
            "  44: clone",
            ") })",
            "",
            "    at PhotonFetcher.<anonymous> (/api/node_modules/@prisma/photon/index.js:65:27)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/api/node_modules/@prisma/photon/index.js:6:65)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

You can reproduce the error using the following example:

**Prisma2 version:** 2.0.0-preview018.2

**Prisma schema**
```
model Customer {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  customerInfo  CustomerInfo
}

model Product {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name          String
  number        Int
  customerInfos CustomerInfo[]
  productGroup  ProductGroup
}

model CustomerInfo {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  customer  Customer
  products  Product[]
}

model ProductGroup {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  products  Product[]
}
```
**GraphQL query**
```
query {
  customers(
    where: {
      customerInfo: {
        products: {
          some: {
            name: { equals: "Cookies" }
            productGroup: { name: { equals: "Food" } }
          }
        }
      }
    }
  ) {
    id
  }
}
```

**Comment by pantharshit00** [comment]
Thanks for the report. I was able to reproduce this in a similar setup.

Here is reproduction for our reference: https://github.com/harshit-test-org/prisma-prisma2-1158
