### ISSUE TITLE
The current Prisma2 tutorial gives a data loss warning when changing schema.prisma with sqlite.

### ISSUE THREAD

**Issue by threehams** [prisma/prisma2#1206]
I'm going through the [tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md). Environment:
- Windows 10
- VS Code terminal (PowerShell)
- yarn 1.15.2
- sqlite (from `prisma2 init`
- prisma2: 2.0.0-preview019
- @prisma/photon: 2.0.0-preview019

Everything works fine up until [step 4.2](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#42-add-another-model). Once I save the file, I'm warned about data loss with this message:

```
   ⚠️   There will be data loss:

     • You are about to alter the column `email` on the `User` table, which still contains 2 non-null values. The data in that column will be lost.
     • You are about to alter the column `name` on the `User` table, which still contains 2 non-null values. The data in that column will be lost.
     • You are about to alter the column `content` on the `Post` table, which still contains 4 non-null values. The data in that column will be lost.
     • You are about to alter the column `createdAt` on the `Post` table, which still contains 4 non-null values. The data in that column will be lost.
     • You are about to alter the column `title` on the `Post` table, which still contains 4 non-null values. The data in that column will be lost.
     • You are about to alter the column `updatedAt` on the `Post` table, which still contains 4 non-null values. The data in that column will be lost.
```

Selecting "no" here throws an error (this is probably a separate issue, but maybe worth mentioning):
```
   > Are you sure you want to apply this change? y/N: N
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:189:13)
    at C:\Users\threehams\workspace\hello-prisma2\node_modules\prisma2\build\index.js:148862:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\threehams\workspace\hello-prisma2\node_modules\prisma2\build\index.js:148861:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\threehams\workspace\hello-prisma2\node_modules\prisma2\build\index.js:148847:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by threehams** [comment]
After going through with it, I think it's just reporting data loss, but it doesn't really wipe anything.

**Comment by malekjaroslav** [comment]
Related: https://github.com/prisma/lift/issues/264
In my case it resets the fields. Meaning when it's date it sets the default date and wipes optional fields.

**Comment by pantharshit00** [comment]
@threehams 

Can you please try this again once with the alpha? 

```sh
npm install -g prisma2@alpha
```

**Comment by threehams** [comment]
On alpha.479, I get a subset of the data loss messages:
```
   ⚠️   There will be data loss:

     • You are about to alter the column `name` on the `User` table, which still contains 2 non-null values. The data in that column will be lost.
     • You are about to alter the column `content` on the `Post` table, which still contains 4 non-null values. The data in that column will be lost.
```

**Comment by malekjaroslav** [comment]
@threehams There is an issue for that in Lift https://github.com/prisma/lift/issues/267 @tomhoule should be looking into it

**Comment by tomhoule** [comment]
On SQLite the messages about data loss when altering a column are not always true. I'm working on weeding out the false positives. Issue: https://github.com/prisma/lift/issues/272
