### ISSUE TITLE
Post-install for @prisma/photon fails

### ISSUE THREAD

**Issue by ehhthing** [prisma/prisma2#1227]
When I run `npm i @prisma/photon`, I get

```
PS C:\Users\Me\Desktop\PROJECT\Prisma> npm i @prisma/photon                                                                                                                                  
> @prisma/photon@2.0.0-preview019 postinstall C:\Users\Me\Desktop\PROJECT\Prisma\node_modules\@prisma\photon
> node scripts/postinstall.js

(node:28580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stderr' of undefined
    at C:\Users\Me\Desktop\PROJECT\Prisma\node_modules\@prisma\photon\scripts\postinstall.js:63:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN prisma@1.0.0 No description
npm WARN prisma@1.0.0 No repository field.

+ @prisma/photon@2.0.0-preview019
updated 1 package and audited 1 package in 7.287s
found 0 vulnerabilities
```

This is on Windows 10, NodeJS 13.5.0, npm 6.13.4

**Comment by janpio** [comment]
Thanks for the report @ehhthing. Tried to reproduce, but could not:

```
E:\Projects\throwaway
λ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (throwaway)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to E:\Projects\throwaway\package.json:

{
  "name": "throwaway",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes)

E:\Projects\throwaway  (throwaway@1.0.0)
λ npm i @prisma/photon

> @prisma/photon@2.0.0-preview019 postinstall E:\Projects\throwaway\node_modules\@prisma\photon
> node scripts/postinstall.js

Error: In order to use "@prisma/photon", please install prisma2. You can install it with "npm add -D prisma2".
    at main (E:\Projects\throwaway\node_modules\@prisma\photon\scripts\postinstall.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN throwaway@1.0.0 No description
npm WARN throwaway@1.0.0 No repository field.

+ @prisma/photon@2.0.0-preview019
added 1 package and audited 1 package in 10.228s
found 0 vulnerabilities
```

What does your `package.json` look like? Mine of course was empty for the testing.

```
λ node -v
v10.18.0

λ npm -v
6.13.4
``

**Comment by pantharshit00** [comment]
@ehhthing Can you also tell us which terminal emulator are you using?

**Comment by ehhthing** [comment]
I've tried both CMD and PowerShell.

To reproduce, you have to already have prisma2 installed.

**Comment by janpio** [comment]
> To reproduce, you have to already have prisma2 installed.

What do you mean by that exactly? `prisma2` node package? Globally, just in your project or both?

**Comment by ehhthing** [comment]
I've always installed it globally, since it's what's recommended by the quick start guide.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
