### ISSUE TITLE
called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [prisma/prisma2#1322]
Hello im having this issue, i use prisma2@alpha and this is the repo https://github.com/GolfredoPerezFernandez/PrismaServer .

```
Error:Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `return await ctx.photon.posts.create()` invocation in C:\Users\owner\Documents\modern-apps\lightmatter\new\src\types\Mutation.ts:353:43

  349
  350 console.log(evarepsilon1Y.length)
  351
  352 console.log(malla.length)
→ 353   return await ctx.photon.posts.create({

Reason: called `Option::unwrap()` on a `None` value in src\libcore\option.rs:378:21

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use �:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (C:\Users\owner\Documents\modern-apps\lightmatter\new\node_modules\@prisma\photon\index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\owner\Documents\modern-apps\lightmatter\new\node_modules\@prisma\photon\index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by malekjaroslav** [comment]
The function that you call `await` in must be `async`. Do you have it async?

**Comment by GolfredoPerezFernandez** [comment]
yes my friend :
 resolve:  async (parent,  {  title, content, imaginaryPartX, imaginaryPartY, IterMAX, NDMAX, dataType, materialType  }, ctx) => {
     ....
  return await ctx.photon.posts.create({
              data: {            
                title:'',
                content:'',
                published: false,
                author: { connect: { id: userId } },
                dataType:'',
                materialType:'',
                imaginaryPartX:{
                  set:imaginaryPartX2
                },
                imaginaryPartY: {
                  set:imaginaryPartY2
                },
                dfImaginaryPartX:{
                   set:malla
                  }
                ,
                dfImaginaryPartY: {
                  set:evarepsilon2Y
                },
                dfRealPartX: {
                  set:malla
                }, 
                dfRealPartY: {
                  set:evarepsilon1Y
                } ,
              },
            })      
        }
      }),

**Comment by lvauvillier** [comment]
Hi,

I have the same error but in a different context.

given the schema :
```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

generator photon {
  provider = "photonjs"
}

enum Tag {
  TAG_1
  TAG_2
  TAG_3
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
  tags      Tag[]
}
```

The following code will make photon crash:

```typescript
import { Photon } from "@prisma/photon";

const photon = new Photon();

async function main() {
  await photon.users.create({
    data: {
      name: "John Doe",
      email: "john.doe@prisma.com",
      posts: {
        create: {
          id: "ck5i6oqgj000001l3ew6p0h04",
          title: "Title",
          published: false,
          tags: {
            set: ["TAG_1", "TAG_2"]
          }
        }
      }
    }
  });

  await photon.posts.update({
    where: {
      id: "ck5i6oqgj000001l3ew6p0h04"
    },
    data: {
      tags: {} // This makes photon crash
    }
  });
}

main();
```

Generated types makes the field `set` optional. This is not properly handled by photon in preview-19 and make the engine crash

```
export declare type PostUpdatetagsInput = {
    set?: Enumerable<Tag> | null;
};
```

**Comment by pantharshit00** [comment]
Hi,

I can confirm this and this is related to https://github.com/prisma/photonjs/issues/279 which was also opened by you. It was actually not fixed and I have reopened it. Please follow that issue now.

**Comment by pantharshit00** [comment]
I think you are passing empty arrays to the set operation. If I don't pass an empty array to the set operation it doesn't panic. 

We need to define the behaviour here and we should also improve the error message when empty arrays are passed into a set operation. I will post a simpler reproduction here soon.
