### ISSUE TITLE
Invalid photon through Docker image

### ISSUE THREAD

**Issue by jean-noelp** [prisma/prisma2#1327]
Hi,

I'm trying to deploy my working web-app including a backend with prisma2.

But when i start the docker image, an error appears with the first "photon.mytable" call:
`Invalid photon.() invocation in /usr/src/app/main.js`
`Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: dev.mytable"))`

This behavior looks like i didn't generated the schema, but i did in dockerfile:

```
FROM node:12.9.1-stretch
LABEL name="myapp-back" version="0.1.0"

WORKDIR /usr/src/app
COPY ./package.json package.json
COPY ./yarn.lock yarn.lock

RUN yarn install --frozen-lockfile --prod

COPY ./tsconfig.json tsconfig.json
COPY ./prisma/schema.prisma prisma/schema.prisma 
RUN yarn generate    <-- calls "prisma2 generate" in package.json

COPY ./src src
RUN yarn build

COPY ./src/schema.graphql ./dist/schema.graphql

ENV NODE_ENV prod
EXPOSE 4000

CMD ["yarn", "start"]
```

Moreover, this backend works fine on my local machine (out of a Docker image).

For info, schema.prisma starts with:
```
generator photon {
  provider      = "photonjs"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}
```

Any idea ?

**Comment by malekjaroslav** [comment]
Do you have your database created?

**Comment by jean-noelp** [comment]
``prisma/dev.db`` is here, but empty :(

But ``node_modules/prisma2/photon/`` is filled. 
(``prisma2 generate`` output was: 
``Generating Photon.js to ./node_modules/@prisma/photon``)

**Comment by malekjaroslav** [comment]
You need to first save your migrations with `prisma2 lift save`, and then during your deployment `prisma2 lift up` to create your database structure

**Comment by jean-noelp** [comment]
with this new line in Dockerfile:
```
COPY ./tsconfig.json tsconfig.json
COPY ./prisma/schema.prisma prisma/schema.prisma 
RUN yarn dbintro.   <-- new line, invoke: "prisma2 lift save && prisma2 lift up"
RUN yarn generate
```

output during docker build:
```
prisma2 lift save && prisma2 lift up
You are trying to create a migration for Sqlite database ev.db.
A database with that name doesn't exist at file:dev.db.
Do you want to create the database?

    Yes            Create new Sqlite database ev.db
    No             Don't create the database
Error in Create Database Dialog
Error: Raw mode is not supported on the current process.stdin, which Ink uses as
 input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#isr
awmodesupported
    at /usr/src/app/node_modules/prisma2/build/index.js:106885:17
    at /usr/src/app/node_modules/prisma2/build/index.js:126056:9
    at commitHookEffectList (/usr/src/app/node_modules/prisma2/build/index.js:19
0512:26)
    at commitPassiveHookEffects (/usr/src/app/node_modules/prisma2/build/index.j
s:190542:11)
    at Object.invokeGuardedCallbackImpl (/usr/src/app/node_modules/prisma2/build
/index.js:190051:10)
    at invokeGuardedCallback (/usr/src/app/node_modules/prisma2/build/index.js:1
90235:31)
    at flushPassiveEffectsImpl (/usr/src/app/node_modules/prisma2/build/index.js
:193399:7)
    at unstable_runWithPriority (/usr/src/app/node_modules/prisma2/build/index.j
s:121924:12)
    at runWithPriority (/usr/src/app/node_modules/prisma2/build/index.js:181530:
10)
    at flushPassiveEffects (/usr/src/app/node_modules/prisma2/build/index.js:193
372:10)
You are trying to apply a migration for Sqlite database ev.db.
A database with that name doesn't exist at file:dev.db.
Do you want to create the database?

    Yes            Create new Sqlite database ev.db
    No             Don't create the database
Error in Create Database Dialog
Error: Raw mode is not supported on the current process.stdin, which Ink uses as
 input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#isr
awmodesupported
    at /usr/src/app/node_modules/prisma2/build/index.js:106885:17
    at /usr/src/app/node_modules/prisma2/build/index.js:126056:9
    at commitHookEffectList (/usr/src/app/node_modules/prisma2/build/index.js:19
0512:26)
    at commitPassiveHookEffects (/usr/src/app/node_modules/prisma2/build/index.j
s:190542:11)
    at Object.invokeGuardedCallbackImpl (/usr/src/app/node_modules/prisma2/build
/index.js:190051:10)
    at invokeGuardedCallback (/usr/src/app/node_modules/prisma2/build/index.js:1
90235:31)
    at flushPassiveEffectsImpl (/usr/src/app/node_modules/prisma2/build/index.js
:193399:7)
    at unstable_runWithPriority (/usr/src/app/node_modules/prisma2/build/index.j
s:121924:12)
    at runWithPriority (/usr/src/app/node_modules/prisma2/build/index.js:181530:
10)
    at flushPassiveEffects (/usr/src/app/node_modules/prisma2/build/index.js:193
372:10)

```

**Comment by malekjaroslav** [comment]
Exactly, `prisma2 lift save` should be done out of docker and committed to your git repository. Then only `prisma2 lift up` runs inside Docker

**Comment by jean-noelp** [comment]
Ok, that's logic in fact.

I tried this. But there is a pb with ``prisma2 lift up``: it requires console interaction, and it is not possible in an automated process like Docker. Is there a "no-interaction" mode ?

**Comment by malekjaroslav** [comment]
try `prisma2 lift up --auto-approve`

**Comment by jean-noelp** [comment]
Thanks, it works! :)

The entire solution:
1- think to backup prisma/migrations at the initial state with ``prisma2 lift save``
2- use this Dockerfile:
```
FROM node:12.9.1-stretch
LABEL name="myapp-back" version="0.1.0"

WORKDIR /usr/src/app
COPY ./package.json package.json
COPY ./yarn.lock yarn.lock

RUN yarn install --frozen-lockfile --prod

COPY ./prisma/schema.prisma prisma/schema.prisma 
COPY ./prisma/migrations prisma/migrations.
RUN yarn generate        <-- prisma2 generate
RUN yarn dbintro           <-- prisma2 lift up --auto-approve

COPY ./tsconfig.json tsconfig.json
COPY ./src src
RUN yarn build

COPY ./src/schema.graphql ./dist/schema.graphql

ENV NODE_ENV production
EXPOSE 4000

CMD ["yarn", "start"]
```

Be careful: this is a versatile server: each time you will reload your image, the database will be reset! Think to use an external image/service to keep data.
