### ISSUE TITLE
Changing the @id field to be different than 'id' breaks prisma.

### ISSUE THREAD

**Issue by KyleBrost** [prisma/prisma2#1355]
Using the example:

   https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql

With the default settings and changing the schema from:

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}

```

To one with the "id" fields changed to "user_id" and "post_id" accordingly

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  user_id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  post_id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}
```

Running the query
```
query {
  feed {
    post_id
    title
    content
    published
    author {
      user_id
      name
      email
    }
  }
}
```
Gives you the following error:

```
Error:
Invalid `new UserClient()` invocation in C:\working\prisma-examples\typescript\graphql\node_modules\@prisma\photon\index.js:296:16

  292 const prefix = this._path.includes('select') ? 'select' : this._path.includes('include') ? 'include' : 'select';
  293 const path = [...this._path, prefix, 'author'];
  294 const newArgs = runtime_1.deepSet(this._args, path, args || true);
  295 this._isList = false;
→ 296 return new UserClient(this._dmmf, this._fetcher, this._queryType, this._rootField, this._clientMethod, newArgs, path, this._isList);{
      where: {
        id: undefined,
    ?   post_id?: ID
      },
      select: {
        author: {}
      }
    })

Argument where of type PostWhereUniqueInput needs at least one argument. Available args are listed in green.

Note: Lines with ? are optional.

    at Document.validate (C:\working\prisma-examples\typescript\graphql\node_modules\@prisma\photon\runtime\index.js:40664:23)
    at UserClient.get _document [as _document] (C:\working\prisma-examples\typescript\graphql\node_modules\@prisma\photon\index.js:209:22)
    at UserClient.then (C:\working\prisma-examples\typescript\graphql\node_modules\@prisma\photon\index.js:230:63)
    at whenResultIsFinished (C:\working\prisma-examples\typescript\graphql\node_modules\graphql-extensions\src\index.ts:171:12)
    at field.resolve (C:\working\prisma-examples\typescript\graphql\node_modules\graphql-extensions\src\index.ts:156:7)
    at resolveFieldValueOrError (C:\working\prisma-examples\typescript\graphql\node_modules\graphql\execution\execute.js:467:18)
    at resolveField (C:\working\prisma-examples\typescript\graphql\node_modules\graphql\execution\execute.js:434:16)
    at executeFields (C:\working\prisma-examples\typescript\graphql\node_modules\graphql\execution\execute.js:275:18)
    at collectAndExecuteSubfields (C:\working\prisma-examples\typescript\graphql\node_modules\graphql\execution\execute.js:713:10)
    at completeObjectValue (C:\working\prisma-examples\typescript\graphql\node_modules\graphql\execution\execute.js:703:10)
```

The documentation say this should work but does not.  Using a ID field named something other than "id" breaks prisma hard.  Any nested resolving of objects does not work.

**Comment by pantharshit00** [comment]
Actually this is related to nexus-prisma solely. If you use raw photon, it works with any name to the ID field.

![image](https://user-images.githubusercontent.com/22195362/72620512-707de380-3965-11ea-8335-724ec067982e.png)


So, closing in favour of https://github.com/prisma-labs/nexus-prisma/issues/574
