### ISSUE TITLE
Upgrade guide (Prisma 1 to Prisma 2) failed at conversion of datamodel 

### ISSUE THREAD

**Issue by hatchli** [prisma/prisma2#1455]
ISSUE: Getting the following error when attempting to convert datamodel to schema, following the upgrade guide for Prisma 1 to Prisma 2:
```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at Object.getCacheDir (C:\Users\Wade\AppData\Roaming\npm-cache\_npx\16244\node_modules\prisma2\download-build\index.js:10992:37)
(node:4512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Installed Prisma 2 CLI pursuant to guide

Attempted to convert datamodel to new schema:
`cat datamodel.prisma | npx prisma2@2.0.0-preview017 convert > schema.prisma`
 replaced with
`cat datamodel.graphql | npx prisma2@2.0.0-preview017 convert > schema.prisma`
because that's what my current setup is with Prisma 1.34.

schema.prisma is created, with the following inside:
`Please wait until the 'prisma query-engine' download completes!`

Repository here: https://github.com/hatchli/ahca/backend

**Comment by nikolasburk** [comment]
Hey @hatchli, I couldn't reproduce this issue. I copied your `datamodel.graphql` file and ran `cat datamodel.graphql | npx prisma2@2.0.0-preview017 convert > schema.prisma`. The command created this `schema.prisma` file for me:

```prisma
model User {
  id               String       @default(cuid()) @id @unique
  name             String
  email            String       @unique
  phone            String?
  password         String
  location         String?
  address          String?
  postal           String?
  resetToken       String?
  resetTokenExpiry Float?
  permissions      Permission[]
  cart             CartItem[]
}

model Item {
  id          String            @default(cuid()) @id @unique
  title       String
  description String
  features    String[]
  highlights  String[]
  promo       ValidPromoCodes[]
  categories  Category[]
  sale        Boolean
  image       String
  largeImage  String
  image1      String?
  largeImage1 String?
  image2      String?
  largeImage2 String?
  price       Int
  createdAt   DateTime          @default(now())
  updatedAt   DateTime          @updatedAt
  user        User
}

model PromoCode {
  id             String            @default(cuid()) @id @unique
  item           Item?
  promotion      ValidPromoCodes[]
  promotionPrice Int
}

model CartItem {
  id             String @default(cuid()) @id @unique
  quantity       Int
  promotionPrice Int?
  item           Item?
  user           User
}

model OrderItem {
  id             String  @default(cuid()) @id @unique
  title          String
  description    String
  image          String
  largeImage     String
  image1         String?
  largeImage1    String?
  image2         String?
  largeImage2    String?
  price          Int
  promotionPrice Int?
  quantity       Int
  user           User?
}

model Order {
  id        String      @default(cuid()) @id @unique
  items     OrderItem[]
  total     Int
  user      User
  charge    String
  createdAt DateTime    @default(now())
  updatedAt DateTime    @updatedAt
}

enum Permission {
  ADMIN
  USER
  GUEST
  ITEMCREATE
  ITEMUPDATE
  ITEMDELETE
  PERMISSIONUPDATE
}

enum ValidPromoCodes {
  LACOUNTY2020
  SFCOUNTY2020
}

enum Category {
  AIR_CONDITIONER
  FURNACE
  WHOLE_HOME_MANIFOLD
  TANKLESS_WATER_SYSTEM
  WATER_SOFTENER
  WATER_FILTRATION
  PLUMBING
  HEATPUMP
  DUCTLESS_MINI_SPLIT
}
```

Does this help? Let me know if you have any further questions 🙂
