### ISSUE TITLE
Improve error when `id` is a String in the schema but an Integer in SQLite.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1490]
Current error
<img width="781" alt="Screen Shot 2020-01-30 at 16 38 51" src="https://user-images.githubusercontent.com/1328733/73464345-0ca0e500-437f-11ea-9dd2-97720e978f41.png">

With DEBUG
```console
j42@Pluto ~/D/p/t/script> env DEBUG="*" ts-node script.ts
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/Users/j42/Dev/prisma-examples/typescript/script/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     datasources: [],
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: true,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined
  prisma-client   }
  prisma-client } +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  prisma-client Request: +12ms
  prisma-client mutation {
  prisma-client   createOneUser(data: {
  prisma-client     email: "alice@prisma.io"
  prisma-client     name: "Alice"
  prisma-client     posts: {
  prisma-client       create: [
  prisma-client         {
  prisma-client           title: "Watch the talks from Prisma Day 2019"
  prisma-client           content: "https://www.prisma.io/blog/z11sg6ipb3i1/"
  prisma-client           published: true
  prisma-client         }
  prisma-client       ]
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     email
  prisma-client     name
  prisma-client     posts {
  prisma-client       id
  prisma-client       title
  prisma-client       content
  prisma-client       published
  prisma-client     }
  prisma-client   }
  prisma-client } +1ms
  prisma-client disconnection promise doesnt exist +6ms
  engine {
  engine   PRISMA_DML_PATH: '/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '63298',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[]',
  engine   CLICOLOR_FORCE: '1'
  engine } +0ms
  engine { cwd: '/Users/j42/Dev/prisma-examples/typescript/script/prisma' } +0ms
  plusX Execution permissions of /Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/runtime/query-engine-darwin are fine +0ms
  engine stderr Printing to stderr for debugging
Listening on 127.0.0.1:63298
 +15ms
  engine Ready after try number 0 +59ms
  agentkeepalive sock[0#localhost:63298:] create, timeout 60000ms +0ms
  agentkeepalive sock[0#localhost:63298:](requests: 1, finished: 0) close, isError: false +6ms
  agentkeepalive sock[1#localhost:63298:] create, timeout 60000ms +1s
  agentkeepalive sock[1#localhost:63298:](requests: 1, finished: 0) error: Error: connect ECONNREFUSED 127.0.0.1:63298
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 63298
}, listenerCount: 2 +1ms
  agentkeepalive sock[1#localhost:63298:](requests: 1, finished: 0) close, isError: true +1ms
  agentkeepalive sock[2#localhost:63298:] create, timeout 60000ms +2s
  agentkeepalive sock[2#localhost:63298:](requests: 1, finished: 0) error: Error: connect ECONNREFUSED 127.0.0.1:63298
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 63298
}, listenerCount: 2 +2ms
  engine {
  engine   error: GotError [RequestError]: connect ECONNREFUSED 127.0.0.1:63298
  engine       at ClientRequest.<anonymous> (/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/runtime/index.js:14275:14)
  engine       at Object.onceWrapper (events.js:313:26)
  engine       at ClientRequest.emit (events.js:228:7)
  engine       at ClientRequest.EventEmitter.emit (domain.js:475:20)
  engine       at ClientRequest.origin.emit (/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/runtime/index.js:63703:11)
  engine       at Socket.socketErrorListener (_http_client.js:406:9)
  engine       at Socket.emit (events.js:228:7)
  engine       at Socket.EventEmitter.emit (domain.js:475:20)
  engine       at emitErrorNT (internal/streams/destroy.js:92:8)
  engine       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) {
  engine     name: 'RequestError',
  engine     code: 'ECONNREFUSED',
  engine     host: 'localhost:63298',
  engine     hostname: 'localhost',
  engine     method: 'POST',
  engine     path: '/',
  engine     socketPath: undefined,
  engine     protocol: 'http:',
  engine     url: 'http://localhost:63298/',
  engine     gotOptions: {
  engine       path: '/',
  engine       protocol: 'http:',
  engine       slashes: true,
  engine       auth: null,
  engine       host: 'localhost:63298',
  engine       port: '63298',
  engine       hostname: 'localhost',
  engine       hash: null,
  engine       search: null,
  engine       query: null,
  engine       pathname: '/',
  engine       href: 'http://localhost:63298/',
  engine       retry: [Object],
  engine       headers: [Object],
  engine       hooks: [Object],
  engine       decompress: true,
  engine       throwHttpErrors: true,
  engine       followRedirect: true,
  engine       stream: false,
  engine       form: false,
  engine       json: true,
  engine       cache: false,
  engine       useElectronNet: false,
  engine       body: '{"query":"mutation {\\n  createOneUser(data: {\\n    email: \\"alice@prisma.io\\"\\n    name: \\"Alice\\"\\n    posts: {\\n      create: [\\n        {\\n          title: \\"Watch the talks from Prisma Day 2019\\"\\n          content: \\"https://www.prisma.io/blog/z11sg6ipb3i1/\\"\\n          published: true\\n        }\\n      ]\\n    }\\n  }) {\\n    id\\n    email\\n    name\\n    posts {\\n      id\\n      title\\n      content\\n      published\\n    }\\n  }\\n}","variables":{}}',
  engine       agent: [Agent],
  engine       method: 'POST',
  engine       forceRefresh: true
  engine     }
  engine   }
  engine } +3s
  prisma-client Error: Engine exited {"target":"exit","timestamp":"2020-01-30T14:53:08.520Z","level":"error","fields":{"message":"255"}}
  prisma-client     at /Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/runtime/index.js:6370:27
  prisma-client     at processTicksAndRejections (internal/process/task_queues.js:94:5)
  prisma-client     at PrismaClientFetcher.request (/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/index.js:41:28) +3s
Error: 
Invalid `const user1 = await prisma.user.create()` invocation in
/Users/j42/Dev/prisma-examples/typescript/script/script.ts:8:35

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
   7   // Seed the database with users and posts
→  8   const user1 = await prisma.user.create(

Engine exited {"target":"exit","timestamp":"2020-01-30T14:53:08.520Z","level":"error","fields":{"message":"255"}}
    at PrismaClientFetcher.request (/Users/j42/Dev/prisma-examples/typescript/script/node_modules/@prisma/client/index.js:62:23)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  prisma-client disconnectionPromise: stopping engine +7ms
  engine Stopping Prisma engine +27ms
  getos { platform: 'darwin', libssl: undefined } +3s
  agentkeepalive sock[2#localhost:63298:](requests: 1, finished: 0) close, isError: true +28ms
```

Directly from engine
```console
j42@Pluto ~/D/p/t/s/prisma> env PRISMA_DML_PATH=schema.prisma ./query-engine-darwin
Printing to stderr for debugging
Listening on 127.0.0.1:4466
{"timestamp":"Jan 30 15:55:44.231","level":"ERROR","target":"prisma","fields":{"message":"PANIC","reason":"Could not convert prisma value to graphqlid: ConversionFailure { from: \"PrismaValue\", to: \"GraphqlId\" }","file":"src/libcore/result.rs","line":1165,"column":5}}
```

**Comment by timsuchanek** [comment]
Thanks @Jolg42! I fixed this in a related issue just today, please confirm next week and reopen if it's still an issue.
