### ISSUE TITLE
Introspection Error Reporting does not output report ID

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1501]
If you break `introspect` and then decide to submit an error report, the CLI does so but does not give you the error report ID:

```
C:\Users\Jan\Documents
λ prisma2 introspect --url mysql://prisma:...@introspection-public-mysql-cluster.cluster-ro-clfeqqifnebj.eu-west-1.rds.amazonaws.com:3306/allsquare --print
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Promise (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:2:980933)
    at new Promise (<anonymous>)
    at IntrospectionEngine.<anonymous> (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:2:979697)
    at Generator.next (<anonymous>)
    at fulfilled (C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\build\index.js:2:974378)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[src\libcore\result.rs:1165:5] called `Result::unwrap()` on an `Err` value: "Table clubs not found"
We successfully received the error report

Thanks a lot for your help! �

```

(The emoji is also not visible in most Windows command lines)

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
