### ISSUE TITLE
[Preview21][connectivity]Ubuntu installation error

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#1509]
Hi there,
I am tring to deploy my project on my cloud server,  first install prisma2 via npm/yarn, which took about serval hours and not success.
I found that one step of installation of prisma2 is downloading debian-openssl, 

```
ubuntu@VM-0-120-ubuntu:~$ npm install -g prisma2         
/usr/local/bin/prisma2 -> /usr/local/lib/node_modules/prisma2/build/index.js

 prisma2@2.0.0-preview021 install /usr/local/lib/node_modules/prisma2
 node download-build/index.js

 Downloading Prisma engines for debian-openssl-1.0.x [    ] 2%^C
ubuntu@VM-0-120-ubuntu:~$ npm install -g prisma2
/usr/local/bin/prisma2 -> /usr/local/lib/node_modules/prisma2/build/index.js

 prisma2@2.0.0-preview021 install /usr/local/lib/node_modules/prisma2
node download-build/index.js

 Downloading Prisma engines for debian-openssl-1.0.x [==                  ] 8%
```

this progress is not a problem in my own computer, but got stuck on in my cloud server(Tencent Cloud)

After a dig,  I found that the downloader connected to 

> s3-eu-west-1-r-w.amazonaws.com

I tried to install openssl lib via  apt-get, but still that installation needs a fresh download from the amazon domain.
I'm wondering if there is a option to skip the download step?
Thanks

**Comment by zzyyzz1992** [comment]
btw, already installed openssl
```
ubuntu@VM-0-120-ubuntu:~$ sudo apt-get -qy install openssl                           
Reading package lists...
Building dependency tree...
Reading state information...
openssl is already the newest version (1.0.2g-1ubuntu4.15).
0 upgraded, 0 newly installed, 0 to remove and 304 not upgraded.
```

**Comment by zzyyzz1992** [comment]
The error log(which drives me crazy):
```
ubuntu@VM-0-120-ubuntu:~$ npm install -g prisma2
/usr/local/bin/prisma2 -> /usr/local/lib/node_modules/prisma2/build/index.js

> prisma2@2.0.0-preview021 install /usr/local/lib/node_modules/prisma2
> node download-build/index.js

> Downloading Prisma engines for debian-openssl-1.0.x [=                   ] 7%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 1,
  retriesLeft: 1 }
> Downloading Prisma engines for debian-openssl-1.0.x [==                  ] 9%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 1,
  retriesLeft: 1 }
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 1,
  retriesLeft: 1 }
> Downloading Prisma engines for debian-openssl-1.0.x [                    ] 2%
```

**Comment by zzyyzz1992** [comment]
```
ubuntu@VM-0-120-ubuntu:~$ npm install -g prisma2
/usr/local/bin/prisma2 -> /usr/local/lib/node_modules/prisma2/build/index.js

> prisma2@2.0.0-preview021 install /usr/local/lib/node_modules/prisma2
> node download-build/index.js

> Downloading Prisma engines for debian-openssl-1.0.x [=======             ] 34%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 1,
  retriesLeft: 1 }
> Downloading Prisma engines for debian-openssl-1.0.x [=====               ] 26%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 1,
  retriesLeft: 1 }
> Downloading Prisma engines for debian-openssl-1.0.x [========            ] 40%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 2,
  retriesLeft: 0 }
(node:3883) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
(node:3883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment]
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/22195362/73654955-ef3b8600-46b2-11ea-84e6-62a97e72a175.png">

I am unable to reproduce this with a Digitalocean ubuntu box:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Can you please paste the output of `cat /etc/os-release/` here? Also, from your profile, looks like you are based in China so I am unsure whether s3 connection are allowed there or not.

**Comment by zzyyzz1992** [comment]
Finnally, I tried 10 times, the last one succeeded!
I dont know if it should be a bug
;)

**Comment by zzyyzz1992** [comment]
Hi @pantharshit00 ,
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
 I've tried dozens of times, the lastest time succeeded, and the progress bar finished very quickly.
I think it's a connectivity problem, and I noticed:
```
> Downloading Prisma engines for debian-openssl-1.0.x [========            ] 40%{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  attemptNumber: 2,
  retriesLeft: 0 }
(node:3883) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
(node:3883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The default retriesLeft is (I guess) 2, maybe it's not a friendly number for poor connectivity users.
After 2 tries, the installation throw a unhandled promise rejections, and hangs forever, the error log only print out using npm, when using yarn, it just shows:
```
ubuntu@VM-0-120-ubuntu:/etc$ yarn global add prisma2
yarn global v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] - prisma...
```

**Comment by zzyyzz1992** [comment]
Plus, it seems that only fresh install needs to download the openssl files

**Comment by janpio** [comment]
Hey @zzyyzz1992, I agree that the 2 retries might not be enough, but I can not reproduce the hanging and unhandled promise rejection:

```
C:\Users\Jan\Documents\throwaway\1509  (1509@1.0.0)
λ npm install prisma2@alpha

> prisma2@2.0.0-alpha.917 install C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2
> node download-build/index.js

> Downloading Prisma engines for windows [                    ] 0%Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/migration-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/introspection-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/prisma.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/prisma.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/migration-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/introspection-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN 1509@1.0.0 No description
npm WARN 1509@1.0.0 No repository field.

+ prisma2@2.0.0-alpha.917
added 1 package from 1 contributor and audited 1 package in 3.416s
found 0 vulnerabilities
```

I can confirm though that Yarn just swallows any error message - but I do not think we can do anything about that:
```
C:\Users\Jan\Documents\throwaway\1509  (1509@1.0.0)
λ yarn add prisma2
yarn add v1.22.0
warning ..\..\package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ prisma2@2.0.0-preview024
info All dependencies
└─ prisma2@2.0.0-preview024
Done in 3.81s.
```

Is it possible that we fixed that problem of the unhandled exception?

I created an issue about the still quite ugly error message, and the number of retries: https://github.com/prisma/prisma2/issues/1855 The "bigger" solution for your problem will probably be https://github.com/prisma/prisma2/issues/1333 which will be implemented soon.

**Comment by zzyyzz1992** [comment]
Hi @janpio , the "bigger" solution(#1333 ) seems a great idea especially for users located in China, we chinese allways have to set a MIRROR after install anything :(
Since the

>  UnhandledPromiseRejectionWarning: Error: unexpected end of file

only happens when performing a fresh install, I can not reproduce that either.

I'll appreciate that if you increase the retriesLeft times and maybe make it a configurable variable too:)

**Comment by janpio** [comment]
Awesome, I'll close this issue then - please follow #1333 to get updates on the implementation of the mirror feature.
