### ISSUE TITLE
Prisma doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1536]
```
❯ yarn prisma2 generate
yarn run v1.21.1
warning package.json: No license field
$ /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/.bin/prisma2 generate
  getos { platform: 'darwin', libssl: undefined } +0ms
  download Setting binary path for query-engine darwin to /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin +0ms
  download Setting binary path for migration-engine darwin to /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/migration-engine +0ms
  download Setting binary path for introspection-engine darwin to /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/introspection-engine-darwin +0ms
  getos { platform: 'darwin', libssl: undefined } +7ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  download Setting binary path for query-engine darwin to /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin +2ms
  getGenerators { binaryPathsWithEngineType:
  getGenerators    { 'query-engine':
  getGenerators       { darwin:
  getGenerators          '/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin' } } } +0ms
  engineCommands getDMMF, override prismaPath = /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin +0ms
  engineCommands getDMMF failed { Error: Command was killed with SIGKILL (Forced termination): /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin cli --dmmf
    at o (/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/build/index.js:2:240546)
    at x (/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/build/index.js:2:2199161)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command:
   '/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin cli --dmmf',
  exitCode: undefined,
  signal: 'SIGKILL',
  signalDescription: 'Forced termination',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false } +8ms
Error: Error: Error: Command was killed with SIGKILL (Forced termination): /Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/query-engine-darwin cli --dmmf
    at Object.<anonymous> (/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/build/index.js:2:2890180)
    at Generator.throw (<anonymous>)
    at rejected (/Users/prisma/prisma/prisma2-e2e-tests/packagers/yarn-workspaces/node_modules/prisma2/build/index.js:2:2886224)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

reproduction available at https://github.com/prisma/prisma2-e2e-tests/tree/feat/packagers/yarn-workspaces/packagers/yarn-workspaces

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this on my machine:
![image](https://user-images.githubusercontent.com/22195362/73920026-a241f480-48ea-11ea-9146-b9e6374ce867.png)

**Comment by steebchen** [comment]
Only happens on my machine, closing for now, will re-open if it continues to be a problem.
