### ISSUE TITLE
`generate` tells me to install wrong Prisma Client package

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1537]
Problem 1:

```
λ npx prisma2@alpha generate
Error: In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project:
npm install @prisma/client
```

This should be `npm install @prisma/client@alpha` or better a specific version. Right now this leads to this situation:

```
C:\Users\Jan\Documents\throwaway\1496                                                                                 
λ npx prisma2@alpha generate                                                                                          
⚠️ @prisma/client@2.0.0-preview021 is not compatible with prisma2@2.0.0-alpha.735. Their versions need to be equal.   
Generated Prisma Client to .\node_modules\@prisma\client                                                              
Done in 13.52s                                                                                                        
```

---

Problem 2:

But as the project is basically empty besides the schema

```
λ tree /F                                  
Folder PATH listing for volume Local Disk  
Volume serial number is 8EC2-149E          
C:.                                        
│   schema.prisma                          
│                                          
└───.vscode                                
        settings.json                      
```

running the `npm install` command will not even work properly:

```
C:\Users\Jan\Documents\throwaway\1496
λ npm install @prisma/client

> @prisma/client@2.0.0-preview021 postinstall C:\Users\Jan\Documents\throwaway\1496\node_modules\@prisma\client
> node scripts/postinstall.js

undefined
Error: In order to use "@prisma/client", please install prisma2. You can install it with "npm add -D prisma2".
    at main (C:\Users\Jan\Documents\throwaway\1496\node_modules\@prisma\client\scripts\postinstall.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\1496\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\1496\package.json'
npm WARN @prisma/client@2.0.0-preview021 requires a peer of prisma2@* but none is installed. You must install peer dependencies yourself.
npm WARN 1496 No description
npm WARN 1496 No repository field.
npm WARN 1496 No README data
npm WARN 1496 No license field.

+ @prisma/client@2.0.0-preview021
added 1 package and audited 1 package in 6.03s
found 0 vulnerabilities
```

This does create `node_modules` and a `package-lock.json`, but no `package.json` - so the project is not in the correct state.

---

```
λ npx prisma2@alpha -v
prisma2@2.0.0-alpha.735, binary version: 08074c311c544a995f4ac86e0ea865ae1845b365
```

**Comment by timsuchanek** [comment]
Will be fixed by https://github.com/prisma/prisma2/pull/1589
