### ISSUE TITLE
Building a Prisma2 server with Google Cloud Build

### ISSUE THREAD

**Issue by auderer** [prisma/prisma2#155]
Prisma2 currently can't be built in a container using the official Docker `node` image, due to missing dependencies such as `openssl`.

I created this custom cloud builder for Google Cloud Build to run `prisma2 generate` as a build step:

https://github.com/auderer/prisma2-cloud-builder

What do you think? Let me know if I'm missing anything in this builder. We should also discuss the dependencies of `prisma2` and maybe create a dedicated Docker image for it, if [docker-node](https://github.com/nodejs/docker-node) is not enough.

**Comment by priley86** [comment]
bump... 

still failing here though.

Dockerfile:
```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

EXPOSE 4000 9229
COPY . /home/app
WORKDIR /home/app
RUN npm install -g prisma2 --unsafe-perm
RUN npm install --unsafe-perm
RUN prisma2 lift save --name 'init'
RUN prisma2 lift up
RUN prisma2 generate
```

Inspecting the container, and @generated/next-prisma is missing:
```
# ls node_modules/\@generated
photon
```

Pretty much unusable for me now - only works on my Mac? 💁‍♂ 

Full build log:
```
| => docker-compose up --build
Building app
Step 1/14 : FROM ubuntu:18.04
 ---> 4c108a37151f
Step 2/14 : RUN apt-get update
 ---> Using cache
 ---> ce61b98ce4ce
Step 3/14 : RUN apt-get install -y curl
 ---> Using cache
 ---> cc41ee99c5ef
Step 4/14 : RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
 ---> Using cache
 ---> a96d81fce430
Step 5/14 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> 5f37da4ea698
Step 6/14 : EXPOSE 4000 9229
 ---> Using cache
 ---> 184d18568c9d
Step 7/14 : COPY . /home/app
 ---> 2e491fb90c5c
Step 8/14 : WORKDIR /home/app
 ---> Running in 9e57e67e02e8
Removing intermediate container 9e57e67e02e8
 ---> 102cd4cf451a
Step 9/14 : RUN rm -rf node_modules
 ---> Running in b7e8ac546692
Removing intermediate container b7e8ac546692
 ---> 6548e1ef317e
Step 10/14 : RUN npm install --unsafe-perm
 ---> Running in ec2fa501b4a7

> bcrypt@3.0.6 install /home/app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[bcrypt] Success: "/home/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> core-js@3.1.4 postinstall /home/app/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> protobufjs@6.8.8 postinstall /home/app/node_modules/protobufjs
> node scripts/postinstall


> graphql-shield@5.3.8 postinstall /home/app/node_modules/graphql-shield
> lightercollective postinstall


                                        
                .,:;;:,.                
           .,:;rrssssssrr;:,.           
      .,:;rssssssssssssssssssr;:,.      
     ;rssssssssssssrrssssssssssssr;     
    .ssssssssssssr:  :rssssssssssss.    
    .rssssssr::;;:,::,:;;::rssssssr.    
     ;ssssss:  ;r:;ss;:r:  ;ssssss;     
     ,sssssss:;r:;ssss;:r::sssssss:     
      ;ssssss:,:rssssssr:,:ssssss;      
      .rssss:  ,;;;;;;;;,  ;ssssr.      
       .rsssr;;;::;::;;;;;;rsssr.       
        .;sssssssr:  :ssssssss;.        
          :rsssssssrrsssssssr:          
           .:rssssssssssssr:.           
             .:;rssssssr;,.             
                .,;;;;,.                


     *** Thank you for using graphql-shield! ***

  Please consider donating to our open collective
       to help us maintain this package.

  https://opencollective.com/graphql-shield/donate

                    ***

npm WARN graphql-backend@ No description
npm WARN graphql-backend@ No repository field.

added 311 packages from 316 contributors and audited 1019 packages in 8.112s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container ec2fa501b4a7
 ---> 4cd94bcfb4a1
Step 11/14 : RUN npm install -g prisma2 --unsafe-perm
 ---> Running in 7dc60d0512ca
/usr/bin/prisma2 -> /usr/lib/node_modules/prisma2/build/index.js

> prisma2@2.0.0-preview-2 install /usr/lib/node_modules/prisma2
> test -f download-build/index.js && node download-build/index.js || echo ""

Downloading alpha/4f33077038a490e4b2c1c260f109309e4a447181/linux-glibc
+ prisma2@2.0.0-preview-2
added 1 package from 1 contributor in 6.63s
Removing intermediate container 7dc60d0512ca
 ---> 4fa69c05230a
Step 12/14 : RUN prisma2 lift save --name 'init'
 ---> Running in c941df15ac5f
Everything up-to-date

Removing intermediate container c941df15ac5f
 ---> 6ede1011d445
Step 13/14 : RUN prisma2 lift up
 ---> Running in 711e3950ee19
🏋️‍ lift up

All migrations are already applied
Removing intermediate container 711e3950ee19
 ---> b69f1ac8a025
Step 14/14 : RUN prisma2 generate
 ---> Running in 8a6591968a80
Generating Photon JS Client to /home/app/node_modules/@generated/photon
Done in 3.63s
Generating Nexus Prisma to /home/app/prisma/node_modules/@generated/nexus-prisma
Done in 49ms

Removing intermediate container 8a6591968a80
 ---> b8c626891ffd
Successfully built b8c626891ffd
Successfully tagged backend_app:latest
Recreating app ... done
Attaching to app
app    | 
app    | > graphql-backend@ start:sh /home/app
app    | > ./scripts/start.sh
app    | 
app    | 
app    | > graphql-backend@ dev /home/app
app    | > ts-node-dev --no-notify --respawn --transpile-only ./src
app    | 
app    | Using ts-node version 8.3.0, typescript version 3.5.2
app    | Error: Cannot find module '@generated/nexus-prisma'
app    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
app    |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
app    |     at Module.require (internal/modules/cjs/loader.js:690:17)
app    |     at require (internal/modules/cjs/helpers.js:25:18)
app    |     at Object.<anonymous> (/home/app/src/index.ts:1:1)
app    |     at Module._compile (internal/modules/cjs/loader.js:776:30)
app    |     at Module._compile (/home/app/node_modules/source-map-support/source-map-support.js:521:25)
app    |     at Module.m._compile (/tmp/ts-node-dev-hook-13080972914325018.js:56:25)
app    |     at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
app    |     at require.extensions.(anonymous function) (/tmp/ts-node-dev-hook-13080972914325018.js:58:14)
app    | [ERROR] 03:04:38 Error: Cannot find module '@generated/nexus-prisma'
^CGracefully stopping... (press Ctrl+C again to force)
Stopping app   ... done
```

**Comment by priley86** [comment]
Looks like my issue above was resolved w/ this (and by removing the `output` property):
https://github.com/prisma/photonjs/issues/56#issuecomment-514338400

Also.. for anyone else looking for some inspiration w/ Prisma2 & Docker, there is a fantastic template started here:
https://github.com/CaptainChemist/docker-prisma

Thanks for this awesome project! 😸

**Comment by divyenduz** [comment]
Is this still an issue? If yes, please post a reproduction, if no, please feel free to close it 🙌 

Besides the awesome docker template above, we also have a docker example now: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
