### ISSUE TITLE
Not Found prisma.gz

### ISSUE THREAD

**Issue by proghjy** [prisma/prisma2#1571]
😿 I'm in Bali, Indonesia, but I can't find that file, so prisma doesn't work. Do others work well? 🤔

```console
prisma      | Error: Not Found https://prisma-builds.s3-eu-west-1.amazonaws.com/master/4f8eb5bd9628db47402dc855ad0b6c7cfc915d46/debiandebian-openssl-1.1.x/prisma.gz
prisma      |     at o.default.retries (/usr/local/lib/node_modules/prisma2/build/index.js:2:2803664)
prisma      |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
prisma      |     at async RetryOperation._fn (/usr/local/lib/node_modules/prisma2/build/index.js:2:2806524) {
prisma      |   attemptNumber: 1,
prisma      |   retriesLeft: 1
prisma      | }
prisma      | Error: Not Found https://prisma-builds.s3-eu-west-1.amazonaws.com/master/4f8eb5bd9628db47402dc855ad0b6c7cfc915d46/debiandebian-openssl-1.1.x/prisma.gz
prisma      |     at o.default.retries (/usr/local/lib/node_modules/prisma2/build/index.js:2:2803664)
prisma      |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
prisma      |     at async RetryOperation._fn (/usr/local/lib/node_modules/prisma2/build/index.js:2:2806524) {
prisma      |   attemptNumber: 2,
prisma      |   retriesLeft: 0
prisma      | }
prisma      | Failed to generate Photon client: Error: Not Found https://prisma-builds.s3-eu-west-1.amazonaws.com/master/4f8eb5bd9628db47402dc855ad0b6c7cfc915d46/debiandebian-openssl-1.1.x/prisma.gz
prisma      |     at o.default.retries (/usr/local/lib/node_modules/prisma2/build/index.js:2:2803664)
prisma      |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
prisma      |     at async RetryOperation._fn (/usr/local/lib/node_modules/prisma2/build/index.js:2:2806524) {
prisma      |   attemptNumber: 2,
prisma      |   retriesLeft: 0
prisma      | }
```

**Comment by proghjy** [comment]
After removing docker image and running it again, it worked fine.
