### ISSUE TITLE
Latest nexus-prisma does not support preview022

### ISSUE THREAD

**Issue by Devlin556** [prisma/prisma2#1640]
Here is an error, when I launching a server with new prisma/client@2.0.0-preview022 and nexus-prisma@0.9.1
```
TypeError: Cannot read property 'map' of undefined
at Object.definition (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus-prisma/src/publisher.ts:126:12)
at SchemaBuilder.walkInputType (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus/src/builder.ts:1365:9)
at SchemaBuilder.walkTypes (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus/src/builder.ts:679:16)
at SchemaBuilder.getFinalTypeMap (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus/src/builder.ts:787:10)
at makeSchemaInternal (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus/src/builder.ts:1585:15)
at Object.makeSchema (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/nexus/src/builder.ts:1630:49)
at Object.<anonymous> (/Users/alexey-milk/Documents/dev/test/test-api/src/graphql/schema/index.ts:20:29)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Module._compile (/Users/alexey-milk/Documents/dev/test/test-api/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:541:25)
at Module.m._compile (/private/var/folders/k7/qsm6_flj5n16vdhsjm6ts3sr0000gp/T/ts-node-dev-hook-748120595857378.js:57:25)
```
I think this error relates to a new type of the `after` argument in prisma-client dmmf. It had kind `scalar` and type `string` in the prev version, now it has kind `object` and type `*WhereInput`

**Comment by pantharshit00** [comment]
We are aware of this. Please follow these issue in the nexus-prisma repository to track progress here: https://github.com/prisma-labs/nexus-prisma/issues/605
and this PR: https://github.com/prisma-labs/nexus-prisma/pull/608
