### ISSUE TITLE
Unclear rust error PANIC

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1671]
Note: This bug report is just about the fact that the error message reports "PANIC" and the user needs to set `DEBUG=*`, not about the actual error.

```
Invalid `prisma.posts.findOne()` invocation in
/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/src/schema.ts:71:18

   67 return ctx.prisma.post.findMany({
   68   where: {
   69     OR: [
   70       { title: { contains: args.searchString } },
→  71       PANIC
    at PrismaClientFetcher.request (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/index.js:89:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

With `DEBUG=*`:

```
  engine stdout { timestamp: 'Feb 21 14:24:17.391',
  level: 'ERROR',
  target: 'prisma',
  fields:
   { message: 'PANIC',
     reason: 'called `Option::unwrap()` on a `None` value',
     file:
      '/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs',
     line: 15,
     column: 40 } } +21ms
  engine { error:
  engine    { Error: socket hang up
  engine        at createHangUpError (_http_client.js:323:15)
  engine        at Socket.socketOnEnd (_http_client.js:426:23)
  engine        at Socket.emit (events.js:203:15)
  engine        at endReadableNT (_stream_readable.js:1145:12)
  engine        at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } } +1ms
  prisma-client Error: PANIC
  prisma-client     at currentRequestPromise.then.catch.e (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/runtime/index.js:1:16175)
  prisma-client     at process._tickCallback (internal/process/next_tick.js:68:7) +8ms
Error: 
Invalid `prisma.posts.findOne()` invocation in
/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/src/schema.ts:71:18

   67 return ctx.prisma.post.findMany({
   68   where: {
   69     OR: [
   70       { title: { contains: args.searchString } },
→  71       PANIC
    at PrismaClientFetcher.request (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/index.js:89:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

reproduction available at https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-sdl-first:

```
git clone https://github.com/prisma/prisma-examples
cd prisma-examples/typescript/graphql-sdl-first
yarn install
prisma2 generate
yarn dev &
pid=$!

sleep 10

curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query {\n  feed {\n    id\n    content\n    author {\n      id\n      name\n      email\n    }\n  }\n}"}' --compressed

kill "$pid"
```

**Comment by pantharshit00** [comment]
I can confirm this. Another issue that also causes `PANIC` without much information: https://github.com/prisma/prisma-client-js/issues/502


Might be related to recent AUMFIDARR merges.

**Comment by janpio** [comment]
Is this still reproducible @pantharshit00?

**Comment by pantharshit00** [comment]
Unable to reproduce this now with preview024:
![image](https://user-images.githubusercontent.com/22195362/77053458-64a9ae80-69f4-11ea-8867-95d8ae29c609.png)


@steebchen report back if you can still reproduce this.
