### ISSUE TITLE
[Prisma 2] ConnectorError

### ISSUE THREAD

**Issue by anddizu** [prisma/prisma2#168]
hen i run this code from [https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#76-use-photon-for-basic-reads-and-writes](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#76-use-photon-for-basic-reads-and-writes)

and show this error:

```
$ yarn start
yarn run v1.17.3
$ ts-node index.ts
(node:9448) UnhandledPromiseRejectionWarning: Error: Error in Photon: 
ConnectorError(QueryError(Error { kind: ToSql(0), cause: Some(WrongType(Type(Text))) }

stack backtrace:
   0: backtrace::backtrace::trace::h5511721bea6fa8d5 (0x10bf209de)
   1: backtrace::capture::Backtrace::new_unresolved::h28f9c9663a9420c8 (0x10bf1fb38)
   2: failure::backtrace::internal::InternalBacktrace::new::hbb41405b6d19ab81 (0x10bf1f4a9)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::h0458ad281d4247c8 (0x10bf1f695)
   4: <sql_connector::error::SqlError as core::convert::From<tokio_postgres::error::Error>>::from::h4d6632d810ab6f89 (0x10b849d5c)
   5: sql_connector::database::postgresql::<impl sql_connector::transactional::Transaction for postgres::transaction::Transaction>::write::ha2ca1483a41de8e3 (0x10b81fe59)
   6: sql_connector::transactional::Transaction::insert::h102a04439344ffff (0x10b4307e4)
   7: sql_connector::transactional::database_writer::create::execute::h2c63144580998c8d (0x10b85e1f1)
   8: sql_connector::transactional::database_writer::<impl connector::database_writer::DatabaseWriter for sql_connector::database::SqlDatabase<T>>::execute::{{closure}}::create::hef864a06474fbea9 (0x10b89ba07)
   9: <sql_connector::database::postgresql::PostgreSql as sql_connector::transactional::Transactional>::with_transaction::h9fe1ec452d2d39e2 (0x10b52dc58)
  10: sql_connector::transactional::database_writer::<impl connector::database_writer::DatabaseWriter for sql_connector::database::SqlDatabase<T>>::execute::h292b3294dffefd85 (0x10b4b2356)
  11: core::executor::write::WriteQueryExecutor::exec_one::h48f2e807cc785823 (0x10b94c006)
  12: core::executor::write::WriteQueryExecutor::execute::h992b6a51be508cce (0x10b94b95b)
  13: core::executor::Executor::exec_all::h5cbc538ae21b3c80 (0x10b96aaa4)
  14: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle::h7d76032243e11158 (0x10b5b29ff)
  15: prisma::http_handler::h5782a9905407eb5f (0x10b54d38f)
  16: <F as actix_web::with::FnWith<T,R>>::call_with::haa4a1a2255bc8611 (0x10b5aa693)
  17: <actix_web::with::WithHandlerFut<T,S,R> as futures::future::Future>::poll::hd3a8444797502a6e (0x10b5b0a12)
  18: actix_web::pipeline::PipelineState<S,H>::poll::h147d5d5368789f0e (0x10b48ab06)
  19: <actix_web::pipeline::Pipeline<S,H> as actix_web::server::handler::HttpHandlerTask>::poll_io::h39e2cc76fc5e8dd4 (0x10b47dfd0)
  20: actix_web::server::h1::Http1Dispatcher<T,H>::poll_handler::hf7d43112cc4ed6f5 (0x10b453e0a)
  21: actix_web::server::h1::Http1Dispatcher<T,H>::poll::h9c1da5bf8f5108dd (0x10b523063)
  22: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll::had9f1b0a81e71dda (0x10b521f39)
  23: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll::had9f1b0a81e71dda (0x10b522df3)
  24: <actix_net::service::and_then::AndThenFuture<A,B> as futures::future::Future>::poll::h15ac475c98adc942 (0x10b47c8c6)
  25: futures::future::chain::Chain<A,B,C>::poll::hb6e62549216884f5 (0x10b478b44)
  26: futures::task_impl::std::set::he4a7d579f87ab972 (0x10b6945bd)
  27: futures::task_impl::Spawn<T>::poll_future_notify::h1a5228822adb903e (0x10b6ad5cf)
  28: tokio_current_thread::CurrentRunner::set_spawn::h6965d5b16e375442 (0x10b68e534)
  29: tokio_current_thread::scheduler::Scheduler<U>::tick::h6c1934358ae3f6a8 (0x10b69a8c5)
  30: tokio_current_thread::Entered<P>::block_on::he3da6e046995d1e4 (0x10b68f0ea)
  31: std::thread::local::LocalKey<T>::with::h6ed9ac0420a84d3b (0x10b6a57c4)
  32: std::thread::local::LocalKey<T>::with::h71f7d0c12da0393f (0x10b6a5d07)
  33: std::thread::local::LocalKey<T>::with::h10c82d1197b9368d (0x10b6a39ec)
  34: std::thread::local::LocalKey<T>::with::h38bd3e3c53efd4ea (0x10b6a4ec8)
  35: tokio::runtime::current_thread::runtime::Runtime::block_on::hbad87c088a1c5a72 (0x10b692952)
  36: std::sys_common::backtrace::__rust_begin_short_backtrace::h690508ce542785d7 (0x10b6ab168)
  37: std::panicking::try::do_call::h1536644c0a3cab79 (0x10b690cbb)
  38: __rust_maybe_catch_panic (0x10bf514cf)
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}::h3508efbc713fc3ba (0x10b6ab9f6)
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf8766009c029bc09 (0x10bf386ce)
  41: std::sys::unix::thread::Thread::new::thread_start::hfdef4649a42cf26c (0x10bf50ace)
  42: _pthread_body (0x7fff6cd782eb)
  43: _pthread_start (0x7fff6cd7b249)))
    at PhotonFetcher.<anonymous> (/Users/anddi/Documents/backend-service/node_modules/@generated/photon/index.js:33:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/anddi/Documents/backend-service/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:9448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Versions (please complete the following information):

nodejs: v12.6.0
Connector: Postgres
Prisma Server: No server
prisma2 CLI: 2.0.0-preview-1
OS: Mac OS X/10.14.5

**Comment by pantharshit00** [comment]
I am unable to reproduce this. 

Can you please tell on which port your postgres server is running?

Also, please share your datamodel(redact any sensitive information). I used the default one that is used in the documentation

**Comment by z2x** [comment]
> I am unable to reproduce this.
> 
> Can you please tell on which port your postgres server is running?
> 
> Also, please share your datamodel(redact any sensitive information). I used the default one that is used in the documentation

postgres：5432
source code: [https://github.com/z2x/prisma2-bug](https://github.com/z2x/prisma2-bug)

**Comment by pantharshit00** [comment]
I am unable to reproduce this now with `prisma2@2.0.0-alpha.62, binary version: 789d98baeec978df37c4faa30d4aba715c230c4d`

![image](https://user-images.githubusercontent.com/22195362/62049507-080f3e80-b22d-11e9-9d0c-d9f5ee0a595b.png)
