### ISSUE TITLE
Error when using generated prisma client: const dmmf = JSON.parse(dmmfString)  SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Tostendo** [prisma/prisma2#1683]
I have this schema:

```sql
CREATE TABLE IF NOT EXISTS organizations (
  id TEXT,
  name TEXT,
  profile JSONB,
  registered DATE,
  logo_image TEXT,
 verification_code SERIAL,
verified BOOLEAN
);
```

and get this model after running `prisma2 introspect` 

```prisma
model organizations {
  id                String    @id
  logo_image        String?
  name              String?
  profile           String?
  registered        DateTime?
  verification_code Int
  verified          Boolean?
}
```

after running `prisma2 generate`and I execute the following code:

```js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const x = await prisma.organizations.create({
    data: {
      id: "some_id",
      verification_code: 123345
    }
  });
  console.log(x);
}

main();
```

I get the following error:

```
const dmmf = JSON.parse(dmmfString)
                  ^
SyntaxError: Unexpected token 
 in JSON at position 6232
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (~/prisma/node_modules/@prisma/client/index.js:3989:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (~/prisma/index.js:1:26)
```

**Comment by janpio** [comment]
Which version of Prisma are you using?
