### ISSUE TITLE
`generate --watch` broken

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma2#1706]
When having a basic schema like so:
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int    @id @default(autoincrement())
  name  String
  email String @unique
  posts Post[]
}

model Post {
  id       Int       @id @default(autoincrement())
  title    String
  text     String
  comments Comment[]
}

model Comment {
  id    Int    @id @default(autoincrement())
  title String
}
```

Now starting `prisma2 generate --watch`
And having a script that looks like so:

```ts
import { PrismaClient } from '@prisma/client'

async function main() {
  const client = new PrismaClient()

  const result = await client.user.findMany({
    select: {
      email: true,
    },
  })


  client.disconnect()
}

main().catch(e => {
  console.error(e)
})
```

Now if I comment out the `email` field in the schema and save, I would expect a typescript error. However, I get a query engine error instead:
```
Invalid `prisma.users.findMany()` invocation:

Failed to validate the query `Error occurred during query validation & transformation:
Query (object)
  ↳ findManyUser (field)
    ↳ User (object)
      ↳ email (field)
        ↳ Field does not exist on enclosing type.` at `.Query.findManyUser.User.email`
    at PrismaClientFetcher.request (/Users/tim/code/prisma-client-performance/node_modules/@prisma/client/index.js:87:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2009',
  meta: {
    query_validation_error: 'Error occurred during query validation & transformation:\n' +
      'Query (object)\n' +
      '  ↳ findManyUser (field)\n' +
      '    ↳ User (object)\n' +
      '      ↳ email (field)\n' +
      '        ↳ Field does not exist on enclosing type.',
    query_position: '.Query.findManyUser.User.email'
  }
}
```

So it seems like the `schema.prisma` file in the runtime folder got updated, while the client didn't get updated properly.
As soon as I do `prisma2 generate` without watch, it's fixed.

**Comment by Jolg42** [comment]
@timsuchanek I did a quick fix: I stop and restart the generator for every change. It works and it's fast. Let me know if you think a better solution is needed ;-)
