### ISSUE TITLE
Violation of unique constraint should give a better error message

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1709]
I have this model:

```prisma
model User {
  email String? @unique
}
```

When I create two records with the same email, I'm violating the unique constraint, e.g.:

```
async function testUserTable() {
  const newUser1 = await prisma.user.create({
    data: {
      email: "alice@prisma.io"
    }
  })
  console.log(newUser1)
  const newUser2 = await prisma.user.create({
    data: {
      email: "alice@prisma.io"
    }
  })
  console.log(newUser2)
}
```

In the console, I see this error:

```
Invalid `const newUser1 = await prisma.user.create()` invocation in
/Users/nikolasburk/Desktop/unique/unique-demo/index.js:6:38

  2 
  3 const prisma = new PrismaClient()
  4 
  5 async function testUserTable() {
→ 6   const newUser1 = await prisma.user.create(PANIC
    at PrismaClientFetcher.request (/Users/nikolasburk/Desktop/unique/unique-demo/node_modules/@prisma/client/index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:35252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~/D/u/unique-demo $ 
```

The error currently doesn't mention that the problem is a violated unique constraint. Including that would be very helpful so that the user immediately knows what's wrong.

**Comment by nikolasburk** [comment]
Ah I realized the error isn't because I'm violating the unique constraint but rather because I didn't have an `@id` field define on thee table. Once I added that, reintrospected and regenerated Prisma Client, I get a better error:

```
node:35487) UnhandledPromiseRejectionWarning: Error: 
Invalid `const newUser1 = await prisma.user.create()` invocation in
/Users/nikolasburk/Desktop/unique/unique-demo/index.js:6:38

  2 
  3 const prisma = new PrismaClient()
  4 
  5 async function main() {
→ 6   const newUser1 = await prisma.user.create(Unique constraint failed on the fields: (`email`)
    at PrismaClientFetcher.request (/Users/nikolasburk/Desktop/unique/unique-demo/node_modules/@prisma/client/index.js:86:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:35487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by janpio** [comment]
But shouldn't that error message be improved as well then?

**Comment by nikolasburk** [comment]
Ideally yes, but I think this error will be gone once AUMFIDAR is completed (I assume this is an issue where the query engine doesn't yet understand models that don't have primary keys...). So probably no need to optimize it IMO.

**Comment by janpio** [comment]
True, good call.
