### ISSUE TITLE
Dataloader is not a constructor

### ISSUE THREAD

**Issue by lglie** [prisma/prisma2#1735]
2.0.0-preview022
OS: centOS 7.5
deploying, The following error message appears, but 2.0.0-preview021 is success,

/usr/local/services/tsf-agent/exec/1301129172/application-2vzjxg8y/group-qabnlwwa/node_modules/@prisma/client/index.js:48
TypeError: Dataloader is not a constructor
at new PrismaClientFetcher (/usr/local/services/tsf-agent/exec/1301129172/application-2vzjxg8y/group-qabnlwwa/node_modules/@prisma/client/index.js:48:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
this.dataloader = new Dataloader(async (requests) => {
at Module._compile (internal/modules/cjs/loader.js:689:30)
at new PrismaClient (/usr/local/services/tsf-agent/exec/1301129172/application-2vzjxg8y/group-qabnlwwa/node_modules/@prisma/client/index.js:282:20)
at Object.<anonymous> (/usr/local/services/tsf-agent/exec/1301129172/application-2vzjxg8y/group-qabnlwwa/dist/authentication/server.js:45:14)

**Comment by pantharshit00** [comment]
Hi @lglie 

Can you please provide a minimal reproduction for this?
