### ISSUE TITLE
Error in query graph construction

### ISSUE THREAD

**Issue by ManAnRuck** [prisma/prisma2#1786]
I get the following error when I try to upsert an item.
```
Error: 
Invalid `prisma.organizations.upsert()` invocation in
/Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:79:26

Error in query graph construction: InputError("The `set` argument was not provided for field `post` on `Organization`")
    at PrismaClientFetcher.request (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/index.js:90:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

<img width="1081" alt="Bildschirmfoto 2020-03-08 um 19 17 17" src="https://user-images.githubusercontent.com/2183135/76168584-77f58800-6171-11ea-84f8-b033fd380768.png">

it's just an array of strings.
and the code intelligence shows me only the set property

<img width="253" alt="Bildschirmfoto 2020-03-08 um 19 24 56" src="https://user-images.githubusercontent.com/2183135/76168745-c22b3900-6172-11ea-8302-00c3f74e5cee.png">

```ts
        const organizationPrepared = {
          ...organization,
          body: undefined,
          'STERNBERG:gruppierung': undefined,
          'STERNBERG:sortierung': undefined,
          membership: undefined,
          meeting: undefined,
          location: undefined,
          keyword: undefined,
          subOrganizationOf: undefined,
          post: {
            set: organization.post,
          },
        };
        return prisma.organization
          .upsert({
            create: organizationPrepared,
            update: organizationPrepared,
            where: { id: organizationPrepared.id },
          })
          .catch(console.log);
      });
```
https://github.com/ManAnRuck/oparl-prisma/blob/42d77996b01049070c497bb847e1c4d8a7e0ca32/src/import/index.ts#L33-L35

```
model Organization {
    id                String        @id
    type              String
    // Body Body
    name              String?
    // membership Membership[]
    // meeting Meeting[]
    // consultation any
    shortName         String?
    post              String[]
    subOrganizationOf Organization?
    organizationType  String?
    classification    String?
    startDate         String?
    endDate           String?
    website           String?
    // # location any
    // externalBody Body
    license           String?
    keyword           String[]
    created           String?
    modified          String?
    web               String?
    deleted           Boolean?
}
```

https://github.com/ManAnRuck/oparl-prisma/blob/42d77996b01049070c497bb847e1c4d8a7e0ca32/prisma/schema.prisma#L10-L34

repo (branch: `issue/set-error`): https://github.com/ManAnRuck/oparl-prisma/tree/issue/set-error

**Comment by pantharshit00** [comment]
Hello @ManAnRuck 

Thanks for the reproduction repository. I tried your reproduction and I was able to reproduce this with `preview023` but I wasn't able to reproduce this with `preview024` which was released yesterday. So can you please try this again with the latest version?
