### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: true', libs/prisma-models/src/fields.rs:61:21

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1979]
```
Error: Error: Schema parsing
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: true', libs/prisma-models/src/fields.rs:61:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: prisma_models::fields::Fields::finalize
  15: prisma_models::internal_data_model::InternalDataModelTemplate::build
  16: prisma::cli::CliCommand::dmmf
  17: prisma::main::{{closure}}
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: tokio::runtime::enter::Enter::block_on
  20: tokio::runtime::context::enter
  21: tokio::runtime::handle::Handle::enter
  22: prisma::main
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  27: std::panicking::try
             at src/libstd/panicking.rs:281
  28: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  29: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  30: main
  31: __libc_start_main
  32: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at Object.<anonymous> (/home/runner/work/introspection-engine-output/introspection-engine-output/node_modules/@prisma/cli/build/index.js:2:2889678)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/introspection-engine-output/introspection-engine-output/node_modules/@prisma/cli/build/index.js:2:2885026)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

in

https://github.com/prisma/introspection-engine-output/blob/f4cd529fd637199cd64151d99bfc2054ee38047f/mysql_127/Basketball_men.log
https://github.com/prisma/introspection-engine-output/blob/f4cd529fd637199cd64151d99bfc2054ee38047f/mysql_127/Mondial.log
https://github.com/prisma/introspection-engine-output/blob/f4cd529fd637199cd64151d99bfc2054ee38047f/mysql_127/VisualGenome.log
https://github.com/prisma/introspection-engine-output/blob/f4cd529fd637199cd64151d99bfc2054ee38047f/mysql_127/tpcd.log

`Basketball_men` for example:
```
generator client { 
    provider = "prisma-client-js"
    output = "../clients/mysql_127/Basketball_men"
  }
datasource db {
  provider = "mysql"
  url      = "mysql://prisma:qd58rcCywPRS4Stk@mysql-introspection-academic.cg7tbvsdqlrs.eu-central-1.rds.amazonaws.com:3306/Basketball_men"
}

model awards_coaches {
  award   String?
  coachID String?
  id      Int      @default(autoincrement()) @id
  lgID    String?
  note    String?
  year    Int?
  coaches coaches? @relation(fields: [coachID, year], references: [coachID, year])

  @@index([coachID], name: "coachID")
  @@index([coachID, year], name: "coachID_2")
  @@index([coachID, year], name: "coachID_3")
  @@index([year, coachID], name: "year")
  @@index([year, coachID], name: "year_2")
  @@index([year, coachID, lgID], name: "year_3")
}

model awards_players {
  award    String
  lgID     String?
  note     String?
  playerID String
  pos      String?
  year     Int
  players  players @relation(fields: [playerID], references: [playerID])

  @@id([playerID, year, award])
  @@index([playerID], name: "playerID")
}

model coaches {
  coachID        String
  lgID           String?
  lost           Int?
  post_losses    Int?
  post_wins      Int?
  stint          Int
  tmID           String
  won            Int?
  year           Int
  teams          teams            @relation(fields: [tmID, year], references: [tmID, year])
  awards_coaches awards_coaches[]

  @@id([coachID, year, tmID, stint])
  @@index([coachID], name: "coachID")
  @@index([tmID, year], name: "tmID")
  @@index([tmID, year], name: "tmID_2")
  @@index([year, coachID], name: "year")
  @@index([year, coachID, lgID], name: "year_2")
  @@index([year, tmID], name: "year_3")
  @@index([year, tmID], name: "year_4")
}

model draft {
  draftFrom      String?
  draftOverall   Int?
  draftRound     Int?
  draftSelection Int?
  draftYear      Int?
  firstName      String?
  id             Int     @default(0) @id
  lastName       String?
  lgID           String?
  playerID       String?
  suffixName     String?
  tmID           String?
  teams          teams?  @relation(fields: [tmID, draftYear], references: [tmID, year])

  @@index([tmID, draftYear], name: "tmID")
}

model players {
  birthCity      String?
  birthCountry   String?
  birthDate      DateTime?
  birthState     String?
  college        String?
  collegeOther   String?
  deathDate      DateTime?
  firstName      String?
  firstseason    Int?
  fullGivenName  String?
  height         Float?
  highSchool     String?
  hsCity         String?
  hsCountry      String?
  hsState        String?
  lastName       String?
  lastseason     Int?
  middleName     String?
  nameGiven      String?
  nameNick       String?
  nameSuffix     String?
  playerID       String           @id
  pos            String?
  race           String?
  useFirst       String?
  weight         Int?
  awards_players awards_players[]
  players_teams  players_teams[]
  player_allstar player_allstar[]
}

model players_teams {
  assists            Int?
  blocks             Int?
  dRebounds          Int?
  fgAttempted        Int?
  fgMade             Int?
  ftAttempted        Int?
  ftMade             Int?
  GP                 Int?
  GS                 Int?
  id                 Int     @default(autoincrement()) @id
  lgID               String?
  minutes            Int?
  note               String?
  oRebounds          Int?
  PF                 Int?
  playerID           String
  points             Int?
  PostAssists        Int?
  PostBlocks         Int?
  PostdRebounds      Int?
  PostfgAttempted    Int?
  PostfgMade         Int?
  PostftAttempted    Int?
  PostftMade         Int?
  PostGP             Int?
  PostGS             Int?
  PostMinutes        Int?
  PostoRebounds      Int?
  PostPF             Int?
  PostPoints         Int?
  PostRebounds       Int?
  PostSteals         Int?
  PostthreeAttempted Int?
  PostthreeMade      Int?
  PostTurnovers      Int?
  rebounds           Int?
  steals             Int?
  stint              Int?
  threeAttempted     Int?
  threeMade          Int?
  tmID               String?
  turnovers          Int?
  year               Int?
  players            players @relation(fields: [playerID], references: [playerID])
  teams              teams?  @relation(fields: [tmID, year], references: [tmID, year])

  @@index([fgAttempted], name: "fgAttempted")
  @@index([fgAttempted], name: "fgAttempted_2")
  @@index([playerID], name: "playerID")
  @@index([tmID, year], name: "tmID")
  @@index([tmID, year], name: "tmID_2")
  @@index([tmID, year], name: "tmID_3")
  @@index([year, tmID], name: "year")
}

model player_allstar {
  assists         Int?
  blocks          Int?
  conference      String?
  d_rebounds      Int?
  fg_attempted    Int?
  fg_made         Int?
  first_name      String?
  ft_attempted    Int?
  ft_made         Int?
  games_played    Int?
  last_name       String?
  league_id       String?
  minutes         Int?
  o_rebounds      Int?
  personal_fouls  Int?
  playerID        String
  points          Int?
  rebounds        Int?
  season_id       Int
  steals          Int?
  three_attempted Int?
  three_made      Int?
  turnovers       Int?
  players         players @relation(fields: [playerID], references: [playerID])

  @@id([playerID, season_id])
  @@index([playerID], name: "player_id")
}

model series_post {
  id                                       Int     @default(autoincrement()) @id
  L                                        Int?
  lgIDLoser                                String?
  lgIDWinner                               String?
  round                                    String?
  series                                   String?
  tmIDLoser                                String?
  tmIDWinner                               String?
  W                                        Int?
  year                                     Int?
  teams_series_post_tmIDLoser_yearToteams  teams?  @relation("series_post_tmIDLoser_yearToteams", fields: [tmIDLoser, year], references: [tmID, year])
  teams_series_post_tmIDWinner_yearToteams teams?  @relation("series_post_tmIDWinner_yearToteams", fields: [tmIDWinner, year], references: [tmID, year])

  @@index([tmIDLoser, year], name: "tmIDLoser")
  @@index([tmIDWinner, year], name: "tmIDWinner")
}

model teams {
  arena                                          String?
  attendance                                     Int?
  awayLost                                       Int?
  awayWon                                        Int?
  bbtmID                                         String?
  confID                                         String?
  confLoss                                       Int?
  confRank                                       Int?
  confWon                                        Int?
  divID                                          String?
  divLoss                                        Int?
  divWon                                         Int?
  d_3pa                                          Int?
  d_3pm                                          Int?
  d_asts                                         Int?
  d_blk                                          Int?
  d_dreb                                         Int?
  d_fga                                          Int?
  d_fgm                                          Int?
  d_fta                                          Int?
  d_ftm                                          Int?
  d_oreb                                         Int?
  d_pf                                           Int?
  d_pts                                          Int?
  d_reb                                          Int?
  d_stl                                          Int?
  d_tmRebound                                    Int?
  d_to                                           Int?
  franchID                                       String?
  games                                          Int?
  homeLost                                       Int?
  homeWon                                        Int?
  lgID                                           String?
  lost                                           Int?
  min                                            Int?
  name                                           String?
  neutLoss                                       Int?
  neutWon                                        Int?
  o_3pa                                          Int?
  o_3pm                                          Int?
  o_asts                                         Int?
  o_blk                                          Int?
  o_dreb                                         Int?
  o_fga                                          Int?
  o_fgm                                          Int?
  o_fta                                          Int?
  o_ftm                                          Int?
  o_oreb                                         Int?
  o_pf                                           Int?
  o_pts                                          Int?
  o_reb                                          Int?
  o_stl                                          Int?
  o_tmRebound                                    Int?
  o_to                                           Int?
  pace                                           Int?
  playoff                                        String?
  rank                                           Int?
  tmID                                           String
  won                                            Int?
  year                                           Int
  coaches                                        coaches[]
  draft                                          draft[]
  players_teams                                  players_teams[]
  series_post_series_post_tmIDLoser_yearToteams  series_post[]   @relation("series_post_tmIDLoser_yearToteams")
  series_post_series_post_tmIDWinner_yearToteams series_post[]   @relation("series_post_tmIDWinner_yearToteams")

  @@id([year, tmID])
  @@index([tmID], name: "tmID")
  @@index([tmID, year], name: "tmID_2")
}
```

Makes this minimized example:

```
model Foo {
  id  Int @id
  one Bar @relation("one", fields: [id], references: [id])
  two Bar @relation(fields: [id], references: [id])
}

model Bar {
  id   Int   @id
  back Foo[]
}
```

**Comment by dpetrick** [comment]
Fix is available on latest alpha now.

**Comment by janpio** [comment]
Can confirm, works 👍
