### ISSUE TITLE
`prisma dev` can't recover from certain rust errors

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#20]
**Datamodel**

```groovy
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photon-js"
  output   = "./generated/photon"
}

model Blog {
  id        Int      @id
  name      String
  viewCount Int
  posts     Post[]
  authors   Author[]
}

model Author {
  id    Int     @id
  name  String?
  posts Post[]
  blog  Blog
}

model Post {
  id    Int      @id
  title String
  tags  String[]
  blog  Blog
  comments Comment[]
}

model Comment {
  id Int @id
  comment String
}

model Comment {
  id Int @id
  comment String
}
```

Two `Comment` is definitely an error, but in development often you just want to copy and paste the previous one and override from there. This is probably not an issue with Rust, but rather we need to gracefully recover from these situations in `prisma dev`. We may either need to automatically restart the rust engine or not kill the rust engine when these sorts of validation errors happen.

**Error**

```
thread 'main' panicked at 'Invariant violation: Inserted key Comment twice, this is a bug and invalidates Weak references. ObjectType { name: "Comment", fields: #Fields Cell# }', query-engine/core/src/schema/builders/cache.rs:62:26
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
/sandbox/node_modules/prisma2/build/index.js:493044
        throw ex;
        ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at child.stdout.d (/sandbox/node_modules/prisma2/build/index.js:96278:25)
    at DestroyableTransform.flush [as _flush] (/sandbox/node_modules/prisma2/build/index.js:96293:9)
    at DestroyableTransform.prefinish (/sandbox/node_modules/prisma2/build/index.js:173352:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (/sandbox/node_modules/prisma2/build/index.js:122896:14)
    at finishMaybe (/sandbox/node_modules/prisma2/build/index.js:122905:5)
    at endWritable (/sandbox/node_modules/prisma2/build/index.js:122918:3)
    at DestroyableTransform.module.exports.3888.Writable.end (/sandbox/node_modules/prisma2/build/index.js:122856:22)
    at Socket.onend (_stream_readable.js:655:10)
```

/cc @Weakky

**Comment by mavilein** [comment]
@ejoebstl fixed this just before Prisma day. Therefore closing it.
