### ISSUE TITLE
Link tables are not working with an introspected database

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma2#280]
I introspected this database https://github.com/catherinedevlin/opensourceshakespeare which I was able to get running on my computer. I was able to see the schema and view the data in postico, but once I ran `prisma2 dev` within the directory with the `schema.prisma` file, the command just hung. Nothing at all happened. I had to quit the process. 

This is a copy of my schema.prisma file:

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://blah:blah@localhost:5432/shakespeare4?schema=public"
}

generator photonjs {
  provider = "photonjs"
}

model Chapter {
  chapterid   Int    @id
  chapter     Int
  description String
  section     Int
  workid      Work

  @@map("chapter")
}

model Character {
  charid        String          @default(cuid()) @id
  abbrev        String?
  characterWork CharacterWork[]
  charname      String
  description   String?
  paragraph     Paragraph[]
  speechcount   Int

  @@map("character")
}

model CharacterWork {
  charid Character
  workid Work

  @@map("character_work")
}

model Paragraph {
  paragraphid   Int       @id
  chapter       Int
  charcount     Int
  charid        Character
  paragraphnum  Int
  paragraphtype String
  phonetictext  String
  plaintext     String
  section       Int
  stemtext      String
  wordcount     Int
  workid        Work

  @@map("paragraph")
}

model Wordform {
  wordformid   Int    @id
  occurences   Int
  phonetictext String
  plaintext    String
  stemtext     String

  @@map("wordform")
}

model Work {
  workid          String          @default(cuid()) @id
  chapter         Chapter[]
  characterWork   CharacterWork[]
  genretype       String
  longtitle       String
  notes           String?
  paragraph       Paragraph[]
  source          String
  title           String
  totalparagraphs Int
  totalwords      Int
  year            Int

  @@map("work")
}
```

**Comment by pantharshit00** [comment]
@etelsv 

Can you please tell me the version of the Prisma2 cli you are using? This was a known bug which got fixed. https://github.com/prisma/lift/issues/10

**Comment by etelsv** [comment]
I updated to prisma2@2.0.0-preview-3.2 and got a new error:
```
Error

   Error: Generic("Generic(\"Model CharacterWork does not have an id field\")")
       at LineStream.out.on.line (/usr/local/lib/node_modules/prisma2/build/index.js:294129:40)
       at LineStream.emit (events.js:197:13)
       at LineStream.EventEmitter.emit (domain.js:439:20)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at LineStream.Readable.push (_stream_readable.js:224:10)
       at LineStream.Transform.push (_stream_transform.js:151:32)
       at LineStream.module.exports.LineStream._pushBuffer (/usr/local/lib/node_modules/prisma2/build/index.js:101280:23)
       at LineStream.module.exports.LineStream._transform (/usr/local/lib/node_modules/prisma2/build/index.js:101272:10)
       at LineStream.Transform._read (_stream_transform.js:190:10)

```

**Comment by pantharshit00** [comment]
Ok looks like the link table is currently not getting supported correctly. There is a note of about this in the limitation: https://github.com/prisma/prisma2/blob/master/docs/limitations.md (last point)

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
