### ISSUE TITLE
Error in lift engine

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#325]
To reproduce, create a project with `prisma2` as the dev dep and basic project setup, save and run a migration. 

Copy this project, remove `node_modules` and run `yarn`, running `yarn prisma2 save --name init` breaks with ENOENT error now. 

```
[migration-engine] error: Error: spawn /Users/divyendusingh/Documents/prisma/p2-315/node_modules/migration-engine ENOENT
Error: Error: Error in lift engine:
    at ChildProcess.child.on.err (/Users/divyendusingh/Documents/prisma/p2-315/node_modules/.bin/prisma2:283105:24)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timsuchanek** [comment]
Not reproducible.
