### ISSUE TITLE
`@default` doesnt work for enum

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#33]
I have this datamodel:

```
model User {
  id: Int @id
  name: String
  role: Role @default(USER)
  posts: Post[]
}

model Post {
  id: Int @id
  title: String
  author: User
}

enum Role {
  USER
  ADMIN
}
```

Because `role` has a `default` value, it can be omitted in the Photon API call:

```ts
import { Photon } from '@generated/photon'

const photon = new Photon()

async function main() {
  await photon.connect()

  const result = await photon.users.create({
    data: { name: 'Niko' }
  })

  console.log(result)
  photon.close()
}

main().catch(e => {
  console.error(e)
  photon.close()
})
```

When I execute this code, I get the following error:

```
$ yarn start
yarn run v1.13.0
$ ts-node main.ts
PhotonError: [
  {
    "error": "ConnectorError(NullConstraintViolation { field_name: \"User.role\" })"
  }
]
    at NodeEngine.handleErrors (/Users/nikolasburk/Desktop/prisma2-test/node_modules/@generated/photon/runtime/index.js:1308:15)
    at /Users/nikolasburk/Desktop/prisma2-test/node_modules/@generated/photon/runtime/index.js:1283:37
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  query: 'mutation {\n  createUser(data: {\n    ' +
    'name: "Niko"\n  }) {\n    id\n    name\n  }\n' +
    '}',
  error: [
    {
      error: 'ConnectorError(NullConstraintViolation { field_name: "User.role" })'
    }
  ],
  logs: '[query-engine/core/src/builders/mutations/root.rs:179] &model.models() = ' +
    '[\n    Model {\n        name: "User",\n        stable_identifier: "",\n      ' +
    '  is_embedded: false,\n        manifestation: None,\n        fields: ' +
    'OnceCell {\n            once: Once {\n                state: Done\n         ' +
    '   },\n            value: UnsafeCell\n        },\n        ' +
    'internal_data_model: #InternalDataModelWeakRef#\n    },\n    Model {\n      ' +
    '  name: "Post",\n        stable_identifier: "",\n        is_embedded: ' +
    'false,\n        manifestation: None,\n        fields: OnceCell {\n          ' +
    '  once: Once {\n                state: Done\n            },\n            ' +
    'value: UnsafeCell\n        },\n        internal_data_model: ' +
    '#InternalDataModelWeakRef#\n    }\n]\n' +
    '[query-engine/connectors/sql-connector/src/database/sqlite.rs:54] ' +
    'visitor::Sqlite::build(q) = (\n    "INSERT INTO `migration_engine`.`User` ' +
    '(`name`) VALUES (?)",\n    [\n        Text(\n            "Niko"\n        )\n  ' +
    '  ]\n)\n',
  isPanicked: false
}
✨  Done in 1.25s.
````

**Comment by schickling** [comment]
We should think through the syntax for this again. Instead of `@default(USER)`, I'd rather be in favor in one of the following options:

1. `@default(.USER)`
2. `@default(Role.USER)`

**Comment by marcjulian** [comment]
How about support of array in default `@default([value1, value2, ...])`? 

An example could be if a user can have multiple roles:

```
model User {
    id          Int       @id
    email       String    @unique
    roles       Role[]    @default([Role.Admin, Role.User])
}

enum Role {
    ADMIN
    USER
}
```

**Comment by nelsonpecora** [comment]
I like the second one (`Role.USER)`. It kinda weirds me out that enum values are effectively global in Prisma 1.x.

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.

**Comment by dpetrick** [comment]
Working on the engine level with direct GraphQL query.

Datamodel needs to change (the one posted is quite old):
```prisma
model User {
  id Int @id
  name String
  role Role @default(value: USER)
  posts Post[]
}

model Post {
  id Int @id
  title String
  author User
}

enum Role {
  USER
  ADMIN
}
```

Query:
```graphql
mutation {
  createOneUser(data:{
    id: 2                 // now needed because of the old implicit autoincrement behaviour on int IDs
    name: "Test"
  }) {
    id
    role
  }
}
```

Result:
```json
{
  "data": {
    "createOneUser": {
      "id": 2,
      "role": "USER"
    }
  }
}
```

**Comment by janpio** [comment]
I adapted the reproduction above to alpha 917:

1. `prisma2 init`
2. Edit `datasource.provider` to `sqlite`, `datasource.url` to `"file:dev.db"`
3. Append schema:
	```
	model User {
	  id Int @id @default(autoincrement())
	  name String
	  role Role @default(value: USER)
	  posts Post[]
	}
	
	model Post {
	  id Int @id
	  title String
	  author User
	}
	
	enum Role {
	  USER
	  ADMIN
	}
	```
	(This also has `autoincrement() to not make explicit ID necessary)
4. `prisma2 migrate save --experimental` and `prisma2 migrate up --experimental`
5. Create `index.js` with content:
	```
	const { PrismaClient } = require('@prisma/client')
	
	const prisma = new PrismaClient()
	
	async function main() {
	  await prisma.connect()
	
	  const result = await prisma.User.create({
	    data: { name: 'Niko' }
	  })
	
	  console.log(result)
	}
	
	main().catch(e => {
	  console.error(e)
	})
	```

This leads to this output:

```
C:\Users\Jan\Documents\throwaway\33>node index.js
{ id: 2, name: 'Niko', role: 'USER' }
^C
C:\Users\Jan\Documents\throwaway\33>
C:\Users\Jan\Documents\throwaway\33>node index.js
{ id: 3, name: 'Niko', role: 'USER' }
^C
C:\Users\Jan\Documents\throwaway\33>node index.js
{ id: 4, name: 'Niko', role: 'USER' }
^C
C:\Users\Jan\Documents\throwaway\33>
```

Is this the expected behavior @nikolasburk and this bug can be closed?

**Comment by nikolasburk** [comment]
Looks great, thanks again :)

**Comment by thilllon** [comment]
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#examples-23

**Comment by johnsonfash** [comment]
enum permission {
  read
  create
  update
  delete
}

model User {
  permission       permission[]       @default([read, update])
}
