### ISSUE TITLE
Collection of QueryEngine related errors

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#35]
Same datamodel/environment as this demo but modified the `main.ts` file to

```ts
import { Photon } from "@generated/photon";

const photon = new Photon();

async function main() {
  await photon.connect();

  const result = await photon.blogs.upsert({
    where: {
      id: 1
    },
    create: {
      name: "Test 1",
      viewCount: 1,
      posts: {
        create: {
          title: "X1"
        }
      }
    },
    update: {
      name: "Test 2",
      viewCount: 2,
      posts: {
        create: {
          title: "X2"
        }
      }
    },
    select: {
      id: true,
      posts: {
        select: {
          id: true
        },
        first: 10
      }
    }
  });

  console.log(result);
  photon.close();
}

main().catch(e => {
  console.error(e);
  photon.close();
});

```

Running this yields the following error: 

```sh
$ [p2]$ yarn ts-node main.ts                                                                                                                                     [1/1837]
yarn run v1.15.2
$ /Users/divyendusingh/Documents/prisma/support/feature/p2/node_modules/.bin/ts-node main.ts

{ Error: [
  {
    "error": "ConnectorError(NullConstraintViolation { field_name: \"Blog.name\" })"
  }
]
    at NodeEngine.handleErrors (/Users/divyendusingh/Documents/prisma/support/feature/p2/node_modules/@generated/photon/runtime/index.js:1305:15)
    at response.json.then.result (/Users/divyendusingh/Documents/prisma/support/feature/p2/node_modules/@generated/photon/runtime/index.js:1280:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  query:
   'mutation {\n  upsertBlog(\n    where: {\n      id: 1\n    }\n    create: {\n      name: "Test 1"\n      viewCount: 1\n      posts: {\n        create: [\n          {\
n            title: "X1"\n          }\n        ]\n      }\n    }\n    update: {\n      name: "Test 2"\n      viewCount: 2\n      posts: {\n        create: [\n          {
\n            title: "X2"\n          }\n        ]\n      }\n    }\n  ) {\n    id\n    name\n    viewCount\n    posts(first: 10) {\n      id\n      title\n      tags\n
 }\n  }\n}',
  error:
   [ { error:
        'ConnectorError(NullConstraintViolation { field_name: "Blog.name" })' } ],
  logs:
   '[query-engine/core/src/schema/builders/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostCreatetagsInput"\n[que
ry-engine/core/src/schema/builders/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostUpdatetagsInput"\n[query-engin
e/core/src/schema/builders/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostUpdatetagsInput"\n[query-engine/core/s
rc/schema/builders/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostCreatetagsInput"\n[query-engine/core/src/schem
a/builders/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostUpdatetagsInput"\n[query-engine/core/src/schema/builde
rs/input_type_builder/mod.rs:41] format!("{}{}{}Input" , model_name , input_object_name , f . name) = "PostUpdatetagsInput"\n[query-engine/core/src/builders/mutations/ro
ot.rs:179] &model.models() = [\n    Model {\n        name: "Blog",\n        stable_identifier: "",\n        is_embedded: false,\n        manifestation: None,\n        fi
elds: OnceCell {\n            once: Once {\n                state: Done\n            },\n            value: UnsafeCell\n        },\n        internal_data_model: #Interna
lDataModelWeakRef#\n    },\n    Model {\n        name: "Author",\n        stable_identifier: "",\n        is_embedded: false,\n        manifestation: None,\n        fiel
ds: OnceCell {\n            once: Once {\n                state: Done\n            },\n            value: UnsafeCell\n        },\n        internal_data_model: #InternalD
ataModelWeakRef#\n    },\n    Model {\n        name: "Post",\n        stable_identifier: "",\n        is_embedded: false,\n        manifestation: None,\n        fields:
OnceCell {\n            once: Once {\n                state: Done\n            },\n            value: UnsafeCell\n        },\n        internal_data_model: #InternalDataM
odelWeakRef#\n    }\n]\n[query-engine/connectors/sql-connector/src/database/sqlite.rs:63] visitor::Sqlite::build(q) = (\n    "SELECT `migration_engine`.`Blog`.`id` FROM
`migration_engine`.`Blog` WHERE `migration_engine`.`Blog`.`id` = ?",\n    [\n        Integer(\n            1\n        )\n    ]\n)\n[query-engine/connectors/sql-connector
/src/database/sqlite.rs:54] visitor::Sqlite::build(q) = (\n    "INSERT INTO `migration_engine`.`Blog` DEFAULT VALUES",\n    []\n)\n',
  isPanicked: false }
✨  Done in 1.33s.
```

**Comment by divyenduz** [comment]
All issues have been created separately. Closing this one.
