### ISSUE TITLE
Deploying to Zeit Now: util.getSystemErrorName is not a function

### ISSUE THREAD

**Issue by ryanking1809** [prisma/prisma2#387]
I've been trying to deploy to Zeit Now using the examples at https://github.com/prisma/prisma2/issues/357 but am getting the following error when running`prisma2 generate` - any idea why? It's a bit cryptic for me.

Repo can be found here: https://github.com/ryanking1809/prisma-test1

Error log:
```
2019-08-21T19:58:54.115Z  yarn info @now/build-utils@canary...
2019-08-21T19:58:54.119Z  yarn info @now/node@canary...
2019-08-21T19:58:54.802Z  yarn add @now/build-utils@0.5.6-canary.50...
2019-08-21T19:58:55.062Z  yarn add v1.17.3
2019-08-21T19:58:55.094Z  info No lockfile found.
2019-08-21T19:58:55.138Z  [1/4] Resolving packages...
2019-08-21T19:58:55.420Z  [2/4] Fetching packages...
2019-08-21T19:58:55.875Z  [3/4] Linking dependencies...
2019-08-21T19:58:55.916Z  [4/4] Building fresh packages...
2019-08-21T19:58:55.923Z  success Saved lockfile.
2019-08-21T19:58:55.929Z  success Saved 1 new dependency.
2019-08-21T19:58:55.929Z  info Direct dependencies
2019-08-21T19:58:55.930Z  └─ @now/build-utils@0.5.6-canary.50
2019-08-21T19:58:55.930Z  info All dependencies
2019-08-21T19:58:55.930Z  └─ @now/build-utils@0.5.6-canary.50
2019-08-21T19:58:55.931Z  Done in 0.88s.
2019-08-21T19:58:55.939Z  yarn add @now/node@0.7.4-canary.61...
2019-08-21T19:58:56.199Z  yarn add v1.17.3
2019-08-21T19:58:56.233Z  info No lockfile found.
2019-08-21T19:58:56.271Z  [1/4] Resolving packages...
2019-08-21T19:58:56.612Z  [2/4] Fetching packages...
2019-08-21T19:58:57.792Z  [3/4] Linking dependencies...
2019-08-21T19:58:57.905Z  [4/4] Building fresh packages...
2019-08-21T19:58:57.912Z  success Saved lockfile.
2019-08-21T19:58:57.918Z  success Saved 2 new dependencies.
2019-08-21T19:58:57.919Z  info Direct dependencies
2019-08-21T19:58:57.919Z  └─ @now/node@0.7.4-canary.61
2019-08-21T19:58:57.920Z  info All dependencies
2019-08-21T19:58:57.920Z  ├─ @now/node@0.7.4-canary.61
2019-08-21T19:58:57.920Z  └─ @types/node@12.7.2
2019-08-21T19:58:57.921Z  Done in 1.73s.
2019-08-21T19:58:58.654Z  running builder.exports.build...
2019-08-21T19:58:58.654Z  [now-builder-debug] downloading user files...
2019-08-21T19:58:58.655Z  [now-builder-debug] download complete [0ms]
2019-08-21T19:58:58.655Z  [now-builder-debug] installing dependencies for user's code...
2019-08-21T19:58:58.657Z  missing `engines` in `package.json`, using default range: 8.10.x
2019-08-21T19:58:58.658Z  installing to /tmp/17708b22/src
2019-08-21T19:58:58.922Z  yarn install v1.17.3
2019-08-21T19:58:58.982Z  [1/4] Resolving packages...
2019-08-21T19:58:59.124Z  [2/4] Fetching packages...
2019-08-21T19:59:05.087Z  [3/4] Linking dependencies...
2019-08-21T19:59:07.641Z  [4/4] Building fresh packages...
2019-08-21T19:59:10.310Z  $ prisma2 generate
2019-08-21T19:59:11.870Z  Error: TypeError: util.getSystemErrorName is not a function
2019-08-21T19:59:11.903Z  error Command failed with exit code 1.
2019-08-21T19:59:11.903Z  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2019-08-21T19:59:11.931Z  Error: Exited with 1
2019-08-21T19:59:11.931Z      at ChildProcess.child.on (/tmp/a5b07cb211138ea0/.build-utils/.builder/node_modules/@now/node/dist/index.js:78198:24)
2019-08-21T19:59:11.931Z      at emitTwo (events.js:126:13)
2019-08-21T19:59:11.931Z      at ChildProcess.emit (events.js:214:7)
2019-08-21T19:59:11.931Z      at maybeClose (internal/child_process.js:925:16)
2019-08-21T19:59:11.931Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-08-21T19:59:12.015Z  done
```

**Comment by ryanking1809** [comment]
Ugh sorry incorrect environment variable names  🤦🏼‍♂️
