### ISSUE TITLE
Installation of prisma2 behind corporate proxy

### ISSUE THREAD

**Issue by kaienbcjdoapwkfldue** [prisma/prisma2#506]
I'm running on Ubuntu 18.04 behind a corportate proxy server and proxy variables are properly set in both the shell and npm config.

When I try to `npm install -g --unsafe-perm prisma2`, I get a timeout error when it tries to download the query- and migration engine during the installation process using the `download` function of the `fetch-engine` module. E.g.:

```
> Downloading linux-glibc-libssl1.1.0 binary [                    ] 0%FetchError: request to https://s3-eu-west-1.amazonaws.com/prisma-native/master/1b0c271f14ca00606f56c93717e228fe48c5603c/linux-glibc-libssl1.1.0/migration-engine.gz failed, reason: connect ETIMEDOUT 52.218.24.18:443
    at ClientRequest.<anonymous> (/home/dmueller/Projects/node_modules/prisma2/download-build/index.js:15010:11)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  message: 'request to https://s3-eu-west-1.amazonaws.com/prisma-native/master/1b0c271f14ca00606f56c93717e228fe48c5603c/linux-glibc-libssl1.1.0/migration-engine.gz failed, reason: connect ETIMEDOUT 52.218.24.18:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  attemptNumber: 1,
  retriesLeft: 1
}

```

Downloading the dependencies with `wget` works fine.

Is `node-fetch` internally used by the `downloadZip` function not honoring proxy settings?

Is there a workaround to finished the installation process manually?

*Edit*

After aborting the installation process upon the timout,  running `prisma init` still works. Creating a demo script does *not* work (`No example selected`), but I can create a blank project. Manually unzipping `prisma.gz` and `migrations-engine.gz` in `node_modules/prisma2`, making them executable and renaming `prisma` to `query-engine-linux-glibc-libssl1.1.0` allows `prisma generate` and `prisma lift save` and `prisma lift up` to work.

**Comment by janpio** [comment]
Thanks for reporting this @kaienbcjdoapwkfldue, we will look into why this doesn't seem to honor the proxy settings.

Your workaround seems like a great temporary solution for the problem though.

(I will create an issue that `prisma2 init` and other commands should fail "better" when no query and migration engine binaries can be found)

**Comment by kaienbcjdoapwkfldue** [comment]
Thanks for responding so swiftly @janpio. The workaround kind of "works", but I cannot create a boilerplate project as I mentioned, so the installation process does not seems to finish properly (of course it does not, and I have no Idea what parts are all missing). Do you have any suggestion how to manually finish it?

**Comment by janpio** [comment]
Unfortunately I do not, but @divyenduz might be. 
@pantharshit00 please take a look at reproducing this as confirmation of the repro. Thanks.

**Comment by divyenduz** [comment]
I think we need to use something like https://www.npmjs.com/package/https-proxy-agent

To be able to override HTTP proxy via env vars.

**Comment by divyenduz** [comment]
> Is node-fetch internally used by the downloadZip function not honoring proxy settings?

@kaienbcjdoapwkfldue How did you provide proxy settings though? At the OS level?

**Comment by kaienbcjdoapwkfldue** [comment]
@divyenduz Proxy settings are provided via environment variables. I remember having had trouble with `node-fetch` in the past. This seems to be a known issue with `node-fetch` and as you correctly pointed out, you need to use some ancillary proxy agent for it.

**Comment by divyenduz** [comment]
@kaienbcjdoapwkfldue : Is there a link to this known issue that you can paste here please?

**Comment by kaienbcjdoapwkfldue** [comment]
@divyenduz Everything points to https://github.com/bitinn/node-fetch/issues/79.

So I suppose you need to use [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) and provide an instance (that probably grabs the https proxy from `process.env["https_proxy"]`) to the [agent option](https://github.com/bitinn/node-fetch#options) of `node-fetch`

**Comment by divyenduz** [comment]
I don't think we use it right now, that is a feature we might include.

**Comment by kaienbcjdoapwkfldue** [comment]
I beg to disagree labelling this a feature, because it effectively prevents users behind proxy servers in their companys to properly install `prisma2`. This not a bug/feature of prisma itself, but of its very installation process, so it really doesn't fall into such catergories.

**Comment by divyenduz** [comment]
@kaienbcjdoapwkfldue I agree, adding a candidate label to this was my way of internally prioritizing it for the next spring, please bear with me for the labelling. This issue is being treated as important regardless 🙏

**Comment by divyenduz** [comment]
Next steps are for me to write a small spec for this [here](https://github.com/prisma/specs/tree/master/cli) and implement it.

**Comment by timsuchanek** [comment]
It's now documented here: https://github.com/prisma/prisma2/blob/master/docs/prisma2-cli.md#using-a-http-proxy-for-the-cli

**Comment by papb** [comment]
> It's now documented here: https://github.com/prisma/prisma2/blob/master/docs/prisma2-cli.md#using-a-http-proxy-for-the-cli

@timsuchanek Where can I find this now? The link is broken

**Comment by janpio** [comment]
https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#proxy-environment-variables should work
