### ISSUE TITLE
Errors/warnings when building on zeit now

### ISSUE THREAD

**Issue by iherger** [prisma/prisma2#535]
Deployment of a standard prisma2/nexus project to zeit now produces the errors/warnings below during build time (the build goes through successfully, though).

It could be `nexus` or `nexus-prisma` related.

Reproduction available via the following repo: https://github.com/iherger/prisma2-now

```
Error: Failed to resolve dependency prettier:
Cannot find module 'prettier' loaded from /tmp/1c608ca4/node_modules/nexus/dist/typegenFormatPrettier.js
    at Promise.all.map (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36473:29)
    at Array.map (<anonymous>)
    at Job.emitDependency (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36466:20)
    at <anonymous>
Error: Failed to resolve dependency bufferutil:
Cannot find module 'bufferutil' loaded from /tmp/1c608ca4/node_modules/ws/lib/buffer-util.js
    at Promise.all.map (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36473:29)
    at Array.map (<anonymous>)
    at Job.emitDependency (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36466:20)
    at <anonymous>
Error: Failed to resolve dependency utf-8-validate:
Cannot find module 'utf-8-validate' loaded from /tmp/1c608ca4/node_modules/ws/lib/validation.js
    at Promise.all.map (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36473:29)
    at Array.map (<anonymous>)
    at Job.emitDependency (/tmp/626a9fdaa395ffce/.build-utils/.builder/node_modules/@now/node/dist/index.js:36466:20)
    at <anonymous>
done
done
```

**Comment by styfle** [comment]
Hi @iherger 

These errors come from the ZEIT Now build system which will analyze all your code and its dependencies to ensure the smallest build possible.

Take a look at [nexus/dist/typegenFormatPrettier.js](https://unpkg.com/browse/nexus@0.11.7/dist/typegenFormatPrettier.js), you'll see a call to `require('prettier')` but since prettier is not installed, the build is warning that it cannot resolve prettier.

If your app runs properly, you can ignore these warnings because that means the code path which calls `require('prettier')` is not executed. If it did execute, you would see a run time error.

**Comment by schickling** [comment]
@timsuchanek @Weakky are we executing `prettier` as part of the build step?

**Comment by soullivaneuh** [comment]
Following [your blog article](https://www.prisma.io/blog/introducing-graphql-nexus-code-first-graphql-server-development-ll6s1yy5cxl5#3-hello-world-with-graphql-yoga), I end up with the same error:

```
app_1  | ✗ server
app_1  | node_modules/nexus/dist/typegenFormatPrettier.js
app_1  | Module not found: Can't resolve 'prettier' in '/app/node_modules/nexus/dist'
```

But it's not a warning, and the server crash.

Using version `0.11.7` of nexus.

What info are you currently looking to fix this issue?

**Comment by soullivaneuh** [comment]
I added `prettier` as a dep, and it seems to work with some warnings:

```
app_1  | node_modules/nexus/dist/typegenAutoConfig.js 78:55-62
app_1  | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
app_1  | node_modules/nexus/dist/typegenAutoConfig.js 208:8-36
app_1  | Critical dependency: the request of a dependency is an expression
app_1  | node_modules/prettier/index.js 10593:17-66
app_1  | Critical dependency: the request of a dependency is an expression
app_1  | node_modules/prettier/index.js 36132:7-46
app_1  | Critical dependency: the request of a dependency is an expression
app_1  | node_modules/prettier/index.js 42576:28-47
app_1  | Critical dependency: the request of a dependency is an expression
app_1  | node_modules/prettier/third-party.js 4368:11-28
app_1  | Critical dependency: the request of a dependency is an expression
app_1  | src/routes/_layout.svelte
app_1  | Module Warning (from ./node_modules/svelte-loader/index.js):
app_1  | A11y: '#' is not a valid href attribute (25:15)
app_1  | 22:           </li>
app_1  | 23:           <li>
app_1  | 24:             <a href="#">
app_1  |                    ^
app_1  | 25:               Mentions légales
app_1  | 26:             </a>
app_1  | node_modules/prettier/parser-glimmer.js 1:127549-127567
app_1  | require.extensions is not supported by webpack. Use a loader instead.
app_1  | node_modules/prettier/parser-glimmer.js 1:127570-127588
app_1  | require.extensions is not supported by webpack. Use a loader instead.
app_1  | node_modules/prettier/parser-glimmer.js 1:127607-127625
app_1  | require.extensions is not supported by webpack. Use a loader instead.
```

So it's a workaround, but I have to setup prettier locally and I don't want that.
