### ISSUE TITLE
[Windows] 'ts-node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by brunocrosier** [prisma/prisma2#614]
Steps taken to reproduce:

1) run `npm i -g prisma2@2.0.0-preview-13`
2) run `prisma2 init hello-world`
3) select GraphQL API starter kit + TypeScript

error: 

```
Downloading the starter kit from GitHub ...
✔  Extracting content to hello-world ...
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
⠙  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

'ts-node' is not recognized as an internal or external command,
operable program or batch file.
```

I am guessing that this is because I don't have `ts-node` installed globally on my PC ? 

When I ran `npm i -g ts-node` and retried, I got the following error:

```

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to hello-world1 ...
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
⠸  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.register (C:\Users\Bruno\AppData\Roaming\npm\node_modules\ts-node\dist\index.js:138:30)
    at Object.<anonymous> (C:\Users\Bruno\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:94:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-graphql@ seed: `ts-node prisma/seed.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-graphql@ seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruno\AppData\Roaming\npm-cache\_logs\2019-09-27T11_01_55_586Z-debug.log
```

**Comment by divyenduz** [comment]
@brunocrosier Does manually running `yarn` or `npm install` in the project folder fix it?

**Comment by brunocrosier** [comment]
@divyenduz yes it does however it means that the user doesn't get the GUI in the terminal telling them how to run `prisma2 dev` and `npm start`

**Comment by divyenduz** [comment]
@brunocrosier : Thanks for the confirmation, this is a bug, it should automatically run. I just wanted to confirm if manually running it fails.

**Comment by divyenduz** [comment]
Just for completion, what Prisma CLI version are you on?

**Comment by brunocrosier** [comment]
2.0.0-preview-13 :)

**Comment by janpio** [comment]
Can confirm for `preview-13`:

```
C:\Users\Jan\Documents\throwaway
λ prisma2 init tsnode

Preparing your starter kit: GraphQL API

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to tsnode ...
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
⠇  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

'ts-node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-graphql@ seed: `ts-node prisma/seed.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-graphql@ seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jan\AppData\Roaming\npm-cache\_logs\2019-09-27T12_02_36_264Z-debug.log
```

**Comment by janpio** [comment]
Can also confirm with current `alpha.216`.

**Comment by divyenduz** [comment]
I can also reproduce this on mac, this is the issue that affects both mac and windows: https://github.com/prisma/prisma2/issues/482

I am closing this one as a duplicate 🙏
If you think that this issue should still be open, please comment here and tag me.
