### ISSUE TITLE
Init flow "printSchema is not a function"

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#616]
On `alpha.216`

To reproduce: 

1. `prisma2 init`
2. `blank project -> sqlite -> JS -> just schema`
3. Error with debug flag:- 

```
$ [prisma]$ prisma2 init p2-photon

  Processing the blank project
  prisma TypeError: templates_1.printSchema is not a function
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58976:136
  prisma     at step (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58888:23)
  prisma     at Object.next (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58869:53)
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58863:71
  prisma     at new Promise (<anonymous>)
  prisma     at module.exports.1903.__awaiter (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58859:12)
  prisma     at run (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58939:20)
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58984:9
  prisma     at commitHookEffectList (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:351366:26)
  prisma     at commitPassiveHookEffects (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:351390:3) +0ms
  prisma TypeError: templates_1.printSchema is not a function
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58976:136
  prisma     at step (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58888:23)
  prisma     at Object.next (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58869:53)
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58863:71
  prisma     at new Promise (<anonymous>)
  prisma     at module.exports.1903.__awaiter (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58859:12)
  prisma     at run (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58939:20)
  prisma     at /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:58984:9
  prisma     at commitHookEffectList (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:351366:26)
  prisma     at commitPassiveHookEffects (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:351390:3) +1ms
```

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
