### ISSUE TITLE
Handle missing global engine

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#629]
While reproducing https://github.com/prisma/prisma2/issues/617 I renamed the `migration-engine.exe` that is found in my `node_modules` folder of the global `prisma2` install to force an error. 

This lead to this error message, that we might want to (or not) handle:

```
C:\Users\Jan\Documents\throwaway\617>prisma2 dev

   Watching for changes in prisma\schema.prisma
   No changes yet


   Generator
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Photon.js Client    not yet generated


   Migrations
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save












   Studio endpoint: http://localhost:5555/
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   d: diff
[migration-engine] error: Error: spawn C:\ProgramData\nvm\v12.10.0\node_modules\prisma2\migration-engine.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\ProgramData\\nvm\\v12.10.0\\node_modules\\prisma2\\migration-engine.exe',
  path: 'C:\\ProgramData\\nvm\\v12.10.0\\node_modules\\prisma2\\migration-engine.exe',
  spawnargs: [Array]
}
Error: spawn C:\ProgramData\nvm\v12.10.0\node_modules\prisma2\migration-engine.exe ENOENT
```

**Comment by janpio** [comment]
Next try was to not remove the file, but break it (by deleting its content). This lead to this error:

```
C:\Users\Jan\Documents\throwaway\617>prisma2 dev

   Watching for changes in prisma\schema.prisma
   No changes yet


   Generator
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Photon.js Client    not yet generated


   Migrations
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save












   Studio endpoint: http://localhost:5555/
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   d: diff
Error: spawn UNKNOWN
```
