### ISSUE TITLE
prisma2 dev command is not working with docker:node-12 and pm2

### ISSUE THREAD

**Issue by LexSwed** [prisma/prisma2#634]
Running main example with `nexus-prisma` and since I need to run three processes (FE, BE, `prisma2 dev`), I decided to use `pm2` to manage them, running them in `docker-compose.command`. prisma process generates this error with no file output:

```bash
app_1  | The above error occurred in the <TabIndexProvider> component:
app_1  |     in TabIndexProvider
app_1  |     in App
app_1  | React will try to recreate this component tree from scratch using the error boundary you provided, App.
app_1  | Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
app_1  | Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
app_1  |     at /usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:425823:17
app_1  |     at /usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:101827:9
app_1  |     at commitHookEffectList (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:255493:26)
app_1  |     at commitPassiveHookEffects (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:255517:3)
app_1  |     at Object.invokeGuardedCallbackImpl (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:248386:10)
app_1  |     at invokeGuardedCallback (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:248564:31)
app_1  |     at commitPassiveEffects (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:256984:9)
app_1  |     at wrapped (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:412534:34)
app_1  |     at flushPassiveEffects (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:257032:5)
app_1  |     at renderRoot (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:257575:3)
```

**Comment by LexSwed** [comment]
rebuilt image and now it just silently does nothing
