### ISSUE TITLE
Error when running `prisma2 dev` or `prisma2 lift save`

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma2#710]
Hi,

I've spent a couple of hours on this now with no success. I've installed a fresh copy of myql 5.7 and also 8 with the same results.

I've tried with various starter kits using both JS and TS. I'm getting prisma to create the DB.

Version: prisma2@2.0.0-preview013.3

This is my db datasource:
```
datasource db {
  provider = "mysql"
  url      = "mysql://root:root@127.0.0.1:3306/e2e"
}
```

Everything works Ok during `prisma2 init` but when it comes to running `prisma2 dev` I get the error below. I've also had some other errors relating to `get_type()` when trying on V8.

Worth noting, previously I the _migrations table was being created so the error below is different to the one I've been experiencing this morning, still, it's not working either way...

```
 Error: Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence
.rs:40] &sql_str = "CREATE TABLE `my_db`.`_Migration` (`revision` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` T
EXT NOT NULL, `datamodel` LONGTEXT NOT NULL, `status` TEXT NOT NULL, `applied` INTEGER NOT NULL, `rolled_back` INTEGER
NOT NULL, `datamodel_steps` LONGTEXT NOT NULL, `database_migration` LONGTEXT NOT NULL, `errors` LONGTEXT NOT NULL, `sta
rted_at` datetime(3) NOT NULL, `finished_at` datetime(3));"
   thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(MySqlError { ER
ROR 1146 (42S02): Table 'my_db._migration' doesn't exist }
   stack backtrace:
      0: backtrace::backtrace::trace
      1: backtrace::capture::Backtrace::new_unresolved
      2: failure::backtrace::internal::InternalBacktrace::new
      3: <failure::backtrace::Backtrace as core::default::Default>::default
      4: prisma_query::connector::mysql::error::<impl core::convert::From<mysql::error::Error> for prisma_query::error:
:Error>::from
      5: prisma_query::connector::metrics::query
      6: <prisma_query::connector::mysql::Mysql as prisma_query::connector::queryable::Queryable>::query
      7: <sql_migration_connector::migration_database::Mysql as sql_migration_connector::migration_database::MigrationD
atabase>::query
      8: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence as migration_connector::migration
_persistence::MigrationPersistence>::update
      9: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::Mi
grationApplier<T>>::apply
     10: migration_engine::commands::apply_migration::ApplyMigrationCommand::handle_migration
     11: <migration_engine::commands::apply_migration::ApplyMigrationCommand as migration_engine::commands::command::Mi
grationCommand>::execute
     12: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::apply_migration
     13: migration_engine::api::rpc::RpcApi::create_sync_handler
     14: tokio_executor::enter::exit
     15: tokio_threadpool::blocking::blocking
     16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     17: futures::future::chain::Chain<A,B,C>::poll
     18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     21: <futures::future::either::Either<A,B> as futures::future::Future>::poll
     22: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     23: <futures::future::either::Either<A,B> as futures::future::Future>::poll
     24: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     26: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
     27: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
     28: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     29: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     30: futures::task_impl::std::set
     31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
     32: std::panicking::try::do_call
     33: __rust_maybe_catch_panic
                at src\libpanic_unwind/lib.rs:82
     34: tokio_threadpool::task::Task::run
     35: tokio_threadpool::worker::Worker::run_task
     36: tokio_threadpool::worker::Worker::run
     37: std::thread::local::LocalKey<T>::with
     38: std::thread::local::LocalKey<T>::with
     39: tokio_reactor::with_default
     40: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
     41: std::thread::local::LocalKey<T>::with
```

**Comment by pantharshit00** [comment]
Thanks for reporting this issue 🙏 . But this specific issue was already reported here: https://github.com/prisma/prisma2/issues/674 so I have to close this one as a duplicate. 

Feel free to post your further findings there or if you feel these two issues are unrelated, please comment here.

**Comment by webnoob** [comment]
@pantharshit00 I updated to the latest preview14 and this issue remained using MySQL 5.7. Exactly the same error I posted originally.

I'm currently in the process of uninstalling MySQL 5.7 and trying with v8 to see if that helps (As my error was different on v8).

**Comment by webnoob** [comment]
I still get an error on MySQL 8.0 as well. I'm using old passwords so that doesn't cause an issue and this time at least the migrations table is created in my DB. 

Note: This is the original error I got on v8.0 using the previous Prisma13 so the update has had no effect on this.

```
Error: Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:
40] &sql_str = "CREATE TABLE `e2e`.`_Migration` (`revision` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` TEXT NOT
 NULL, `datamodel` LONGTEXT NOT NULL, `status` TEXT NOT NULL, `applied` INTEGER NOT NULL, `rolled_back` INTEGER NOT NULL
, `datamodel_steps` LONGTEXT NOT NULL, `database_migration` LONGTEXT NOT NULL, `errors` LONGTEXT NOT NULL, `started_at`
datetime(3) NOT NULL, `finished_at` datetime(3));"
thread 'tokio-runtime-worker-0' panicked at 'get data_type', src\libcore\option.rs:1190:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace
/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace
/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: migration_engine::main::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  13: rust_begin_unwind
             at src\libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  15: core::option::expect_failed
             at src\libcore/option.rs:1190
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: sql_schema_describer::mysql::SqlSchemaDescriber::get_table
  19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  21: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe
  22: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::da
tabase_migration_inferrer::DatabaseMigrationInferrer<sql_migration_connector::sql_migration::SqlMigration>>::infer
  23: <migration_engine::commands::infer_migration_steps::InferMigrationStepsCommand as migration_engine::commands::comm
and::MigrationCommand>::execute
  24: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::infer_migration_steps
  25: migration_engine::api::rpc::RpcApi::create_sync_handler
  26: tokio_executor::enter::exit
  27: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  28: futures::future::chain::Chain<A,B,C>::poll
  29: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  30: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  31: futures::future::chain::Chain<A,B,C>::poll
  32: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  33: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  34: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  35: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  36: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  37: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  38: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  39: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  40: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  41: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  42: futures::task_impl::std::set
  43: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  44: std::panicking::try::do_call
  45: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  46: tokio_threadpool::task::Task::run
  47: tokio_threadpool::worker::Worker::run_task
  48: tokio_threadpool::worker::Worker::run
  49: std::thread::local::LocalKey<T>::with
  50: std::thread::local::LocalKey<T>::with
  51: std::thread::local::LocalKey<T>::with
  52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  53: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at ChildProcess.child.on (C:\Users\Allan\AppData\Roaming\nvm\v11.10.1\node_modules\prisma2\build\index.js:194613:35)
    at ChildProcess.emit (events.js:197:13)
    at ChildProcess.EventEmitter.emit (domain.js:446:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
(node:10540) ExperimentalWarning: The fs.promises API is experimental
```

**Comment by janpio** [comment]
Thanks @webnoob, I can confirm this with MySQL 5.7 and reopened #674. We will collect more information over there (feel free to add your +1).
