### ISSUE TITLE
Prisma 2 generate fails on Windows

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma2#711]
The earlier versions were ok but `alpha.231` fails with this error:
```
> prisma2 generate

Error:
    Error: F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/photon-generator/index.js is not executable. Please run chmod +x node_modules/prisma2/build/photon-generator/index.js
        at new GeneratorProcess (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:564634:19)
        at new Generator (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:192475:33)
        at Object.<anonymous> (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:682016:43)
        at Generator.next (<anonymous>)
        at F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:681965:71
        at new Promise (<anonymous>)
        at module.exports.__awaiter (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:681961:12)
        at p_map_1.default.stopOnError (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:682008:94)
        at F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:692242:21
```

The problem is that the `photon-generator/index.js` has shebang on top of the file (`#!/usr/bin/env node`) which doesn't work on Windows 😞

**Comment by janpio** [comment]
Same is happening for `prisma2 dev`: https://github.com/prisma/prisma2/issues/674

**Comment by timsuchanek** [comment]
Thanks for reporting! We just fixed it for the latest alpha.
