### ISSUE TITLE
Error in migration engine when using with sample Chinook dataset

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#724]
The Chinook dataset is the [default example used in the SQLite documentation](https://www.sqlitetutorial.net/sqlite-sample-database/). I am exploring how it can be used with the Prisma Framework. 

You can explore the dataset and use a runnable Photon.js script [in the `prisma-datasets` repo](https://github.com/prisma/prisma-datasets/tree/master/datasets/sqlite/chinook).

Since we don't support introspection for SQLite yet, I've written out the Prisma schema by hand:

```prisma
datasource chinook {
  provider = "sqlite"
  url      = "file:./chinook.db"
}

generator photon {
  provider = "photonjs"
}

model Album {
  id     Int     @id @map("AlbumId")
  title  String  @map("title") @default("n/a")
  artist Artist  @map("ArtistId")
  // relation field not present in DB schema
  tracks Track[]

  @@map("albums")
}

model Artist {
  id     Int     @id @map("ArtistId")
  name   String? @map("Name")
  // relation field not present in DB schema
  albums Album[]

  @@map("artists")
}

model Customer {
  id         Int     @id @map("CustomerId")
  firstName  String  @map("FirstName")
  lastName   String  @map("LastName")
  company    String? @map("Company")
  address    String? @map("Address")
  city       String? @map("City")
  state      String? @map("State")
  country    String? @map("Country")
  postalCode String? @map("PostalCode")
  phone      String? @map("Phone")

  fax        String?   @map("Fax")
  email      String    @map("Email")
  supportRep Employee? @map("SupportRepId")
  // relation field not present in DB schema
  invoices   Invoice[]

  @@map("customers")
}

model Employee {
  id         Int        @id @map("EmployeeId")
  firstName  String     @map("FirstName")
  lastName   String     @map("LastName")
  title      String?    @map("Title")
  // birthDate  DateTime?  @map("BirthDate")
  // hireDate   DateTime?  @map("HireDate")
  address    String?    @map("Address")
  city       String?    @map("City")
  state      String?    @map("State")
  country    String?    @map("Country")
  postalCode String?    @map("PostalCode")
  phone      String?    @map("Phone")
  fax        String?    @map("Fax")
  email      String?    @map("Email")
  // relation field not present in DB schema
  customers  Customer[]
  // reportsTo  Employee? @map("reportsTo")

  @@map("employees")
}

model Genre {
  id     Int     @id @map("GenreId")
  name   String?
  // relation field not present in DB schema
  tracks Track[]

  @@map("genres")
}

model InvoiceItem {
  id        Int     @id @map("InvoiceLineId")
  invoice   Invoice @map("InvoiceId")
  track     Track   @map("TrackId")
  unitPrice Float   @map("UnitPrice")
  quantity  Int     @map("Quantity")

  @@map("invoice_items")
}

model Invoice {
  id                Int           @id @map("InvoiceId")
  customer          Customer      @map("CustomerId")
  // invoiceDate       DateTime      @map("InvoiceDate")
  billingAddress    String?       @map("BillingAddress")
  billingCity       String?       @map("BillingCity")
  billingState      String?       @map("BillingState")
  billingCountry    String?       @map("BillingCountry")
  billingPostalCode String?       @map("BillingPostalCode")
  total             Float         @map("Total")
  // relation field not present in DB schema
  invoiceItems      InvoiceItem[]

  @@map("invoices")
}

model MediaType {
  id   Int     @id @map("MediaTypeId")
  name String? @map("Name")

  @@map("mediaTypes")
}

model PlaylistTrack {
  id       String   @id @default(cuid())
  playlist Playlist @map("PlaylistId")
  track    Track    @map("TrackId")

  @@map("playlist_track")
}

model Playlist {
  id   Int     @id @map("PlaylistId")
  name String? @map("Name")

  @@map("playlists")
}

model Track {
  id           Int           @id @map("TrackId")
  name         String        @map("Name")
  album        Album?        @map("AlbumId")
  mediaType    MediaType     @map("MediaTypeId")
  genre        Genre?        @map("GenreId")
  composer     String?       @map("Composer")
  milliseconds Int           @map("Milliseconds")
  bytes        Int           @map("Bytes")
  unitPrice    Float         @map("UnitPrice")
  // relation field not present in DB schema
  invoiveItems InvoiceItem[]

  @@map("tracks")
}
```

For reference, these are the SQL statements to build the DB schema:

```sql
CREATE TABLE "albums" ( 
  [AlbumId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Title] NVARCHAR(160) NOT NULL
  [ArtistId] INTEGER NOT NULL
  FOREIGN KEY ([ArtistId]) REFERENCES "artists" ([ArtistId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "artists" ( 
  [ArtistId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Name] NVARCHAR(120) 
)
CREATE TABLE "customers" ( 
  [CustomerId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [FirstName] NVARCHAR(40) NOT NULL
  [LastName] NVARCHAR(20) NOT NULL
  [Company] NVARCHAR(80)
  [Address] NVARCHAR(70)
  [City] NVARCHAR(40)
  [State] NVARCHAR(40)
  [Country] NVARCHAR(40)
  [PostalCode] NVARCHAR(10)
  [Phone] NVARCHAR(24)
  [Fax] NVARCHAR(24)
  [Email] NVARCHAR(60) NOT NULL
  [SupportRepId] INTEGER
  FOREIGN KEY ([SupportRepId]) REFERENCES "employees" ([EmployeeId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "employees" ( 
  [EmployeeId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [LastName] NVARCHAR(20) NOT NULL
  [FirstName] NVARCHAR(20) NOT NULL
  [Title] NVARCHAR(30)
  [ReportsTo] INTEGER
  [BirthDate] DATETIME
  [HireDate] DATETIME
  [Address] NVARCHAR(70)
  [City] NVARCHAR(40)
  [State] NVARCHAR(40)
  [Country] NVARCHAR(40)
  [PostalCode] NVARCHAR(10)
  [Phone] NVARCHAR(24)
  [Fax] NVARCHAR(24)
  [Email] NVARCHAR(60)
  FOREIGN KEY ([ReportsTo]) REFERENCES "employees" ([EmployeeId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "genres" ( 
  [GenreId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Name] NVARCHAR(120) 
)
CREATE TABLE "invoice_items" ( 
  [InvoiceLineId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [InvoiceId] INTEGER NOT NULL
  [TrackId] INTEGER NOT NULL
  [UnitPrice] NUMERIC(10,2) NOT NULL
  [Quantity] INTEGER NOT NULL
  FOREIGN KEY ([InvoiceId]) REFERENCES "invoices" ([InvoiceId]) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY ([TrackId]) REFERENCES "tracks" ([TrackId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "invoices" ( 
  [InvoiceId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [CustomerId] INTEGER NOT NULL
  [InvoiceDate] DATETIME NOT NULL
  [BillingAddress] NVARCHAR(70)
  [BillingCity] NVARCHAR(40)
  [BillingState] NVARCHAR(40)
  [BillingCountry] NVARCHAR(40)
  [BillingPostalCode] NVARCHAR(10)
  [Total] NUMERIC(10,2) NOT NULL
  FOREIGN KEY ([CustomerId]) REFERENCES "customers" ([CustomerId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "media_types" ( 
  [MediaTypeId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Name] NVARCHAR(120) 
)
CREATE TABLE "playlist_track" ( 
  [PlaylistId] INTEGER NOT NULL
  [TrackId] INTEGER NOT NULL
  CONSTRAINT [PK_PlaylistTrack] PRIMARY KEY ([PlaylistId]
  [TrackId])
  FOREIGN KEY ([PlaylistId]) REFERENCES "playlists" ([PlaylistId]) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY ([TrackId]) REFERENCES "tracks" ([TrackId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
CREATE TABLE "playlists" ( 
  [PlaylistId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Name] NVARCHAR(120) 
)
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE sqlite_stat1(tbl,idx,stat)
CREATE TABLE "tracks" ( 
  [TrackId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  [Name] NVARCHAR(200) NOT NULL
  [AlbumId] INTEGER
  [MediaTypeId] INTEGER NOT NULL
  [GenreId] INTEGER
  [Composer] NVARCHAR(220)
  [Milliseconds] INTEGER NOT NULL
  [Bytes] INTEGER
  [UnitPrice] NUMERIC(10,2) NOT NULL
  FOREIGN KEY ([AlbumId]) REFERENCES "albums" ([AlbumId]) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY ([GenreId]) REFERENCES "genres" ([GenreId]) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY ([MediaTypeId]) REFERENCES "media_types" ([MediaTypeId]) ON DELETE NO ACTION ON UPDATE NO ACTION 
)
```

While it's possible to generate Phton.js and use it in an application, it's not possible to run `prisma2 dev`. This fails with the following error:

```
$ npx prisma2 dev

 Error

   Error: Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREA
TE TABLE IF NOT EXISTS \"lift\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL,
 \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migrat
ion\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
   thread 'tokio-runtime-worker-0' panicked at 'type 'datetime' is not supported here yet', libs/sql-schema-describer/src/sqlite.rs:313:14
   stack backtrace:
      0: std::panicking::default_hook::{{closure}}
      1: std::panicking::default_hook
      2: migration_engine::main::{{closure}}
      3: std::panicking::rust_panic_with_hook
      4: std::panicking::begin_panic
      5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
      6: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
      7: sql_schema_describer::sqlite::SqlSchemaDescriber::get_table
      8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
      9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
     10: <sql_schema_describer::sqlite::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe
     11: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inf
errer::DatabaseMigrationInferrer<sql_migration_connector::sql_migration::SqlMigration>>::infer
     12: <migration_engine::commands::infer_migration_steps::InferMigrationStepsCommand as migration_engine::commands::command::MigrationComman
d>::execute
     13: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::infer_migration_steps
     14: migration_engine::api::rpc::RpcApi::create_sync_handler
     15: tokio_executor::enter::exit
     16: tokio_threadpool::blocking::blocking
     17: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
     23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     25: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
     26: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
     27: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     28: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     29: futures::task_impl::std::set
     30: std::panicking::try::do_call
     31: __rust_maybe_catch_panic
     32: tokio_threadpool::task::Task::run
     33: tokio_threadpool::worker::Worker::run_task
     34: tokio_threadpool::worker::Worker::run
     35: std::thread::local::LocalKey<T>::with
     36: std::thread::local::LocalKey<T>::with
     37: std::thread::local::LocalKey<T>::with
     38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
     39: std::thread::local::LocalKey<T>::with
     40: std::thread::local::LocalKey<T>::with
   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
       at ChildProcess.<anonymous> (/Users/nikolasburk/Desktop/prisma-datasets/datasets/sqlite/chinook/node_modules/prisma2/build/index.js:5791
98:35)
       at ChildProcess.emit (events.js:196:13)
       at ChildProcess.EventEmitter.emit (domain.js:471:20)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
```

I caught this part in the error message:

```
thread 'tokio-runtime-worker-0' panicked at 'type 'datetime' is not supported here yet',
```

However, the error persists even after I remove the `DateTime` fields from the Prisma schema.

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engine/pull/107 fixes three small issues with SQlite that crashed `prisma dev` _on a new sqlite database with the chinook datamodel_. Once this is released, you should be able to work with the chinook schema on SQLite, but it won't work with an already populated database, because I think we need the introspection flow for that (the migration engine can't deal with an already populated database with no migrations table at the moment).

To work with an existing chinook database with data, I think we need introspection. I think @do4gr has started working on intropsection for sqlite.

**Comment by nikolasburk** [comment]
This seems to be fixed now 👍
