### ISSUE TITLE
[Windows] `prisma2 dev` crashes on blank Postgres project

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#733]
```
C:\Users\Jan\Documents\throwaway>prisma2 init blank_postgres

 SUCCESS  The blank_postgres directory was created!
 SUCCESS  Prisma is connected to your database at localhost

┌─ Next steps ───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                    │
│   Navigate into the project directory:                                                                             │
│   $ cd blank_postgres                                                                                              │
│                                                                                                                    │
│   Start Prisma's development mode to enable access to                                                              │
│   Prisma Studio and watch schema.prisma for changes:                                                               │
│   $ prisma2 dev                                                                                                    │
│                                                                                                                    │
│   Start the REST API server (in a new terminal window/tab):                                                        │
│   $ npm run dev                                                                                                    │
│                                                                                                                    │
│   Learn more about Prisma 2:                                                                                       │
│   https://github.com/prisma/prisma2/                                                                               │
│                                                                                                                    │
│   If you encounter any issues, please report them here:                                                            │
│   https://github.com/prisma/prisma-examples/issues/new                                                             │
│                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


C:\Users\Jan\Documents\throwaway>cd blank_postgres

C:\Users\Jan\Documents\throwaway\blank_postgres>prisma2 dev
 ERROR  Oops, an unexpected error occured!
Error in migration engine: thread 'main' panicked at 'CommandError(Generic { code: 1000, error: "QueryError(QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(\"42501\"), message: \"permission denied for database postgres\", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"d:\\\\pginstaller_12.auto\\\\postgres.windows-x64\\\\src\\\\backend\\\\catalog\\\\aclchk.c\"), line: Some(3489), routine: Some(\"aclcheck_error\") }) }\n\nstack backtrace:\n   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new_unresolved\n   2: failure::backtrace::internal::InternalBacktrace::new\n   3: <failure::backtrace::Backtrace as core::default::Default>::default\n   4: prisma_query::connector::postgres::error::<impl core::convert::From<tokio_postgres::error::Error> for prisma_query::error::Error>::from\n   5: prisma_query::connector::metrics::query\n   6: <prisma_query::connector::postgres::PostgreSql as prisma_query::connector::queryable::Queryable>::query_raw\n   7: <sql_migration_connector::migration_database::PostgreSql as sql_migration_connector::migration_database::MigrationDatabase>::query_raw\n   8: <sql_migration_connector::SqlMigrationConnector as migration_connector::MigrationConnector>::initialize\n   9: migration_engine::migration_engine::MigrationEngine<C,D>::init\n  10: migration_engine::migration_engine::MigrationEngine<C,D>::new\n  11: migration_engine::api::rpc::RpcApi::new\n  12: migration_engine::api::rpc::RpcApi::new_async\n  13: migration_engine::main\n  14: std::rt::lang_start::{{closure}}\n  15: std::rt::lang_start_internal::{{closure}}\n             at src\\libstd/rt.rs:49\n      std::panicking::try::do_call\n             at src\\libstd/panicking.rs:292\n  16: __rust_maybe_catch_panic\n             at src\\libpanic_unwind/lib.rs:80\n  17: std::panicking::try\n             at src\\libstd/panicking.rs:271\n      std::panic::catch_unwind\n             at src\\libstd/panic.rs:394\n      std::rt::lang_start_internal\n             at src\\libstd/rt.rs:48\n  18: main\n  19: _tmainCRTStartup\n  20: mainCRTStartup\n  21: sqlite3GenerateConstraintChecks\n  22: sqlite3GenerateConstraintChecks\n)\n\nstack backtrace:\n   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new_unresolved\n   2: failure::backtrace::internal::InternalBacktrace::new\n   3: <failure::backtrace::Backtrace as core::default::Default>::default\n   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from\n   5: <migration_connector::error::ConnectorError as core::convert::From<prisma_query::error::Error>>::from\n   6: <sql_migration_connector::SqlMigrationConnector as migration_connector::MigrationConnector>::initialize\n   7: migration_engine::migration_engine::MigrationEngine<C,D>::init\n   8: migration_engine::migration_engine::MigrationEngine<C,D>::new\n   9: migration_engine::api::rpc::RpcApi::new\n  10: migration_engine::api::rpc::RpcApi::new_async\n  11: migration_engine::main\n  12: std::rt::lang_start::{{closure}}\n  13: std::rt::lang_start_internal::{{closure}}\n             at src\\libstd/rt.rs:49\n      std::panicking::try::do_call\n             at src\\libstd/panicking.rs:292\n  14: __rust_maybe_catch_panic\n
          at src\\libpanic_unwind/lib.rs:80\n  15: std::panicking::try\n             at src\\libstd/panicking.rs:271\n
    std::panic::catch_unwind\n             at src\\libstd/panic.rs:394\n      std::rt::lang_start_internal\n
 at src\\libstd/rt.rs:48\n  16: main\n  17: _tmainCRTStartup\n  18: mainCRTStartup\n  19: sqlite3GenerateConstraintChecks\n  20: sqlite3GenerateConstraintChecks\n)" })', migration-engine/core/src/main.rs:161:27
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: migration_engine::main::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  13: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:335
  14: migration_engine::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:49
  17: std::panicking::try::do_call
             at src\libstd/panicking.rs:292
  18: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  19: std::panicking::try
             at src\libstd/panicking.rs:271
  20: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src\libstd/rt.rs:48
  22: main
  23: _tmainCRTStartup
  24: mainCRTStartup
  25: sqlite3GenerateConstraintChecks
  26: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this on macOS.

> \"permission denied for database postgres\"

This suggests that your user doesn't have enough permission. Can you please check whether your user does have enough permission to create databases, schemas and read the "postgres" database.

**Comment by janpio** [comment]
No idea, and the setup doesn't exist like this any more.

No matter why it is happening, it should be handled properly with an error message that tells the user what is the problem.

**Comment by janpio** [comment]
`localhost` on Windows.

**Comment by pantharshit00** [comment]
This issue now looks like a duplicate of https://github.com/prisma/prisma2/issues/735 which I can reproduce.

Have a look there and I think we can close this

**Comment by pantharshit00** [comment]
<img width="932" alt="Screenshot 2019-10-18 at 12 45 57 PM" src="https://user-images.githubusercontent.com/22195362/67073685-402b7b00-f1a5-11e9-85d6-b7c629504add.png">

I am unable to reproduce this on a mac with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`

I am also unable to reproduce this on windows:
![image](https://user-images.githubusercontent.com/22195362/67076103-217bb300-f1aa-11e9-8ada-6d458e03c19a.png)

Version: `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`

**Comment by pantharshit00** [comment]
@janpio Are you able to still reproduce this one?

**Comment by janpio** [comment]
No, also got success this time.
