### ISSUE TITLE
binaryTargets with native regression

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#750]
Prisma generate for the following config fails with a 404. 

```
generator photon {
  provider = "photonjs"
  binaryTargets = ["native"]
}
```

On catalina, the error is different but the link from the "Downloading" message is still a 404. 

```
divyendusingh [prisma2-native]$ prisma2 generate
  getos { platform: 'darwin', libssl: undefined } +0ms
  getos { platform: 'darwin', libssl: undefined } +26ms
  getos { platform: 'darwin', libssl: undefined } +9ms
  getos { platform: 'darwin', libssl: undefined } +399ms
  download Downloading https://s3-eu-west-1.amazonaws.com/prisma-native/master/188a379c9b8c6650e5812f9bdb7407d7b197692f/native/prisma.gz to /Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/query-engine-native +0ms
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.getCacheDir (/Users/divyendusingh/.nvm/versions/node/v10.16.3/lib/node_modules/prisma2/build/index.js:396877:37)
```

**Comment by timsuchanek** [comment]
Fixed in latest alpha. We'll shortly release a patch for this.
