### ISSUE TITLE
prisma2 dev stuck at migrations, lift up panics

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#820]
```
$ prisma2 --version
prisma2@2.0.0-alpha.267, binary version: cdf5c04cbfa7228f05eadb07656db1781b9d5b85
```

`prisma2 dev` was stuck for me at lift, so I tried `prisma2 lift save --name init && prisma2 lift up` and got the error: 

```
Checking the datasource for potential data loss...
Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREATE TABLE `p2-s
tudio-267`.`_Migration` (`revision` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` TEXT NOT NULL, `datamodel` LONGTEXT NOT NULL, `status` TEXT
 NOT NULL, `applied` INTEGER NOT NULL, `rolled_back` INTEGER NOT NULL, `datamodel_steps` LONGTEXT NOT NULL, `database_migration` LONGTEXT NOT NULL,
 `errors` LONGTEXT NOT NULL, `started_at` datetime(3) NOT NULL, `finished_at` datetime(3));"
thread 'tokio-runtime-worker-0' panicked at 'The model User already exists in this Datamodel. It is not possible to create it once more.', migratio
n-engine/core/src/migration/datamodel_calculator.rs:62:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: migration_engine::main::{{closure}}
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::continue_panic_fmt
   8: std::panicking::begin_panic_fmt
   9: <migration_engine::migration::datamodel_calculator::DataModelCalculatorImpl as migration_engine::migration::datamodel_calculator::DataModelCa
lculator>::infer
We successfully received the error report
To help us even more, please create an issue at https://github.com/prisma/prisma2/issues/new
mentioning the report id 306.
```

Telemetry report ID: 306

`schema.prisma`

```groovy
datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3306/p2-studio-267"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Comment by bearbytes** [comment]
I'm having the same problem:
```
$ prisma2 --version
prisma2@2.0.0-alpha.270, binary version: cdf5c04cbfa7228f05eadb07656db1781b9d5b85

$ prisma2 lift up
Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREATE TABLE IF NOT EXI
STS \"lift\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \
"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT 
NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
thread 'tokio-runtime-worker-0' panicked at 'Deserializing the database migration failed.: Error("missing field `original_steps`", line: 0, column: 0)',
 src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: migration_engine::main::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: rust_begin_unwind
             at src/libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  16: <sql_migration_connector::SqlMigrationConnector as migration_connector::MigrationConnector>::deserialize_database_migration
  17: <migration_engine::commands::list_migrations::ListMigrationStepsCommand as migration_engine::commands::command::MigrationCommand>::execute
```

**Comment by divyenduz** [comment]
@bearbytes Thanks, can you please create a new GH issue with a minimal reproduction.
