### ISSUE TITLE
Error: Could not find photon package at @generated/photon.

### ISSUE THREAD

**Issue by ZaneH** [prisma/prisma2#826]
Prisma2 CLI Version: `prisma2@2.0.0-preview015`

dependencies:
nexus: `^0.12.0-beta.14`
nexus-prisma: `^0.5.0`

devDependencies:
@prisma/sdk: `^0.0.21`
prisma2: `2.0.0-preview015`

``` bash
$ yarn generate
yarn run v1.19.0
$ npm -s run generate:prisma && npm -s run generate:nexus
> Downloading darwin binary for query-engine [====================] 100%

Generating Photon.js to /Users/zane/repos/project/mono-repo/packages/prisma/node_modules/@generated/photon
Done in 13.30s


/Users/zane/repos/project/mono-repo/node_modules/nexus-prisma/src/dmmf/utils.ts:14
    throw new Error(
          ^
Error: Plugin nexus-prisma failed on "onInstall" hook:

Error: Could not find photon package at @generated/photon. Check that you have configured your Photon generator block in schema.prisma correctly and run prisma generate.
    at Object.exports.get (/Users/zane/repos/project/mono-repo/node_modules/nexus-prisma/src/dmmf/utils.ts:14:11)
    at new SchemaBuilder (/Users/zane/repos/project/mono-repo/node_modules/nexus-prisma/src/builder.ts:162:38)
    at Object.build (/Users/zane/repos/project/mono-repo/node_modules/nexus-prisma/src/builder.ts:89:19)
    at Object.onInstall (/Users/zane/repos/project/mono-repo/node_modules/nexus-prisma/src/index.ts:43:16)
    at Object.triggerOnInstall (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/plugins.ts:113:36)
    at /Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1481:22
    at Array.forEach (<anonymous>)
    at buildTypesInternal (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1480:21)
    at makeSchemaInternal (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1528:9)
    at Object.makeSchema (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1579:9)
    at Object.triggerOnInstall (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/plugins.ts:115:15)
    at /Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1481:22
    at Array.forEach (<anonymous>)
    at buildTypesInternal (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1480:21)
    at makeSchemaInternal (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1528:9)
    at Object.makeSchema (/Users/zane/repos/project/mono-repo/node_modules/nexus/src/builder.ts:1579:9)
    at Object.<anonymous> (/Users/zane/repos/project/mono-repo/packages/prisma/src/schema.ts:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/Users/zane/repos/project/mono-repo/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I run `l` within `./packages/prisma/prisma` I get:
```
total 72
drwxr-xr-x   6 zane  staff   192B Oct 21 16:22 .
drwxr-xr-x  13 zane  staff   416B Oct 22 12:35 ..
drwxr-xr-x   5 zane  staff   160B Oct 22 12:04 migrations
-rw-r--r--   1 zane  staff    20K Oct 22 11:42 schema.prisma
-rw-r--r--   1 zane  staff    15K Oct 21 11:43 seed.ts
```

This was working ~preview013. Hopefully, this was helpful– I can include any additional information as well.

**Comment by ZaneH** [comment]
I've rolled back my Prisma version to preview013.3 and everything is in a 'working' state again. Unfortunately, it's not totally working. I've got the `t.crud.orders()` method to generate my `orders` query– however, `t.crud.order()` results in an error when using the `order` query.

Here's my code to expose the crud methods:
```
...
t.crud.order()
t.crud.orders()
...
```

Here's the error that appears when using `{ order(where: { id: "<id>" }) { id } }` query

<details>
<summary>Click to expand error log</summary>

```
yarn run v1.19.0
$ ts-node-dev --no-notify --respawn --transpileOnly ./src
Using ts-node version 8.4.1, typescript version 3.6.3
🚀 Server ready at: http://localhost:4000
⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#6-using-the-graphql-api
Error: 
Invalid `photon.orders.findOne()` invocation in /Users/zane/repos/project/node_modules/graphql-extensions/src/index.ts:155:61

{
  where: {
    id: {
      kind: 'StringValue',
      value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
      block: false,
      loc: {
        start: 22,
        end: 60,
        startToken: {
          kind: 'String',
          start: 22,
          end: 60,
          line: 2,
          column: 21,
          value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
          prev: {
            kind: ':',
            start: 20,
            end: 21,
            line: 2,
            column: 19,
            value: undefined,
            prev: {
              kind: 'Name',
              start: 18,
              end: 20,
              line: 2,
              column: 17,
              value: 'id',
              prev: {
                kind: '{',
                start: 17,
                end: 18,
                line: 2,
                column: 16,
                value: undefined,
                prev: {
                  kind: ':',
                  start: 15,
                  end: 16,
                  line: 2,
                  column: 14,
                  value: undefined,
                  prev: {
                    kind: 'Name',
                    start: 10,
                    end: 15,
                    line: 2,
                    column: 9,
                    value: 'where',
                    prev: {
                      kind: '(',
                      start: 9,
                      end: 10,
                      line: 2,
                      column: 8,
                      value: undefined,
                      prev: {
                        kind: 'Name',
                        start: 4,
                        end: 9,
                        line: 2,
                        column: 3,
                        value: 'order',
                        prev: {
                          kind: '{',
                          start: 0,
                          end: 1,
                          line: 1,
                          column: 1,
                          value: undefined,
                          prev: {
                            kind: '<SOF>',
                            start: 0,
                            end: 0,
                            line: 0,
                            column: 0,
                            value: undefined,
                            prev: null,
                            next: "[Circular]"
                          },
                          next: "[Circular]"
                        },
                        next: "[Circular]"
                      },
                      next: "[Circular]"
                    },
                    next: "[Circular]"
                  },
                  next: "[Circular]"
                },
                next: "[Circular]"
              },
              next: "[Circular]"
            },
            next: "[Circular]"
          },
          next: {
            kind: '}',
            start: 60,
            end: 61,
            line: 2,
            column: 59,
            value: undefined,
            prev: "[Circular]",
            next: {
              kind: ')',
              start: 61,
              end: 62,
              line: 2,
              column: 60,
              value: undefined,
              prev: "[Circular]",
              next: {
                kind: '{',
                start: 63,
                end: 64,
                line: 2,
                column: 62,
                value: undefined,
                prev: "[Circular]",
                next: {
                  kind: 'Name',
                  start: 69,
                  end: 71,
                  line: 3,
                  column: 5,
                  value: 'id',
                  prev: "[Circular]",
                  next: {
                    kind: 'Name',
                    start: 76,
                    end: 86,
                    line: 4,
                    column: 5,
                    value: 'adminNotes',
                    prev: "[Circular]",
                    next: {
                      kind: '}',
                      start: 89,
                      end: 90,
                      line: 5,
                      column: 3,
                      value: undefined,
                      prev: "[Circular]",
                      next: {
                        kind: '}',
                        start: 91,
                        end: 92,
                        line: 6,
                        column: 1,
                        value: undefined,
                        prev: "[Circular]",
                        next: {
                          kind: '<EOF>',
                          start: 93,
                          end: 93,
                          line: 7,
                          column: 1,
                          value: undefined,
                          prev: "[Circular]",
                          next: null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        endToken: {
          kind: 'String',
          start: 22,
          end: 60,
          line: 2,
          column: 21,
          value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
          prev: {
            kind: ':',
            start: 20,
            end: 21,
            line: 2,
            column: 19,
            value: undefined,
            prev: {
              kind: 'Name',
              start: 18,
              end: 20,
              line: 2,
              column: 17,
              value: 'id',
              prev: {
                kind: '{',
                start: 17,
                end: 18,
                line: 2,
                column: 16,
                value: undefined,
                prev: {
                  kind: ':',
                  start: 15,
                  end: 16,
                  line: 2,
                  column: 14,
                  value: undefined,
                  prev: {
                    kind: 'Name',
                    start: 10,
                    end: 15,
                    line: 2,
                    column: 9,
                    value: 'where',
                    prev: {
                      kind: '(',
                      start: 9,
                      end: 10,
                      line: 2,
                      column: 8,
                      value: undefined,
                      prev: {
                        kind: 'Name',
                        start: 4,
                        end: 9,
                        line: 2,
                        column: 3,
                        value: 'order',
                        prev: {
                          kind: '{',
                          start: 0,
                          end: 1,
                          line: 1,
                          column: 1,
                          value: undefined,
                          prev: {
                            kind: '<SOF>',
                            start: 0,
                            end: 0,
                            line: 0,
                            column: 0,
                            value: undefined,
                            prev: null,
                            next: "[Circular]"
                          },
                          next: "[Circular]"
                        },
                        next: "[Circular]"
                      },
                      next: "[Circular]"
                    },
                    next: "[Circular]"
                  },
                  next: "[Circular]"
                },
                next: "[Circular]"
              },
              next: "[Circular]"
            },
            next: "[Circular]"
          },
          next: {
            kind: '}',
            start: 60,
            end: 61,
            line: 2,
            column: 59,
            value: undefined,
            prev: "[Circular]",
            next: {
              kind: ')',
              start: 61,
              end: 62,
              line: 2,
              column: 60,
              value: undefined,
              prev: "[Circular]",
              next: {
                kind: '{',
                start: 63,
                end: 64,
                line: 2,
                column: 62,
                value: undefined,
                prev: "[Circular]",
                next: {
                  kind: 'Name',
                  start: 69,
                  end: 71,
                  line: 3,
                  column: 5,
                  value: 'id',
                  prev: "[Circular]",
                  next: {
                    kind: 'Name',
                    start: 76,
                    end: 86,
                    line: 4,
                    column: 5,
                    value: 'adminNotes',
                    prev: "[Circular]",
                    next: {
                      kind: '}',
                      start: 89,
                      end: 90,
                      line: 5,
                      column: 3,
                      value: undefined,
                      prev: "[Circular]",
                      next: {
                        kind: '}',
                        start: 91,
                        end: 92,
                        line: 6,
                        column: 1,
                        value: undefined,
                        prev: "[Circular]",
                        next: {
                          kind: '<EOF>',
                          start: 93,
                          end: 93,
                          line: 7,
                          column: 1,
                          value: undefined,
                          prev: "[Circular]",
                          next: null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        source: {
          body: '{\n  order(where: {id: "ffcafdc2-2080-4721-b560-bbd7665b805c"}) {\n    id\n    adminNotes\n  }\n}\n',
          name: 'GraphQL request',
          locationOffset: {
            line: 1,
            column: 1
          }
        }
      }
    }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  }
}

Argument id: Got invalid value 
{
  kind: 'StringValue',
  value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
  block: false,
  loc: {
    start: 22,
    end: 60,
    startToken: {
      kind: 'String',
      start: 22,
      end: 60,
      line: 2,
      column: 21,
      value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
      prev: {
        kind: ':',
        start: 20,
        end: 21,
        line: 2,
        column: 19,
        value: undefined,
        prev: {
          kind: 'Name',
          start: 18,
          end: 20,
          line: 2,
          column: 17,
          value: 'id',
          prev: {
            kind: '{',
            start: 17,
            end: 18,
            line: 2,
            column: 16,
            value: undefined,
            prev: {
              kind: ':',
              start: 15,
              end: 16,
              line: 2,
              column: 14,
              value: undefined,
              prev: {
                kind: 'Name',
                start: 10,
                end: 15,
                line: 2,
                column: 9,
                value: 'where',
                prev: {
                  kind: '(',
                  start: 9,
                  end: 10,
                  line: 2,
                  column: 8,
                  value: undefined,
                  prev: {
                    kind: 'Name',
                    start: 4,
                    end: 9,
                    line: 2,
                    column: 3,
                    value: 'order',
                    prev: {
                      kind: '{',
                      start: 0,
                      end: 1,
                      line: 1,
                      column: 1,
                      value: undefined,
                      prev: {
                        kind: '<SOF>',
                        start: 0,
                        end: 0,
                        line: 0,
                        column: 0,
                        value: undefined,
                        prev: null,
                        next: "[Circular]"
                      },
                      next: "[Circular]"
                    },
                    next: "[Circular]"
                  },
                  next: "[Circular]"
                },
                next: "[Circular]"
              },
              next: "[Circular]"
            },
            next: "[Circular]"
          },
          next: "[Circular]"
        },
        next: "[Circular]"
      },
      next: {
        kind: '}',
        start: 60,
        end: 61,
        line: 2,
        column: 59,
        value: undefined,
        prev: "[Circular]",
        next: {
          kind: ')',
          start: 61,
          end: 62,
          line: 2,
          column: 60,
          value: undefined,
          prev: "[Circular]",
          next: {
            kind: '{',
            start: 63,
            end: 64,
            line: 2,
            column: 62,
            value: undefined,
            prev: "[Circular]",
            next: {
              kind: 'Name',
              start: 69,
              end: 71,
              line: 3,
              column: 5,
              value: 'id',
              prev: "[Circular]",
              next: {
                kind: 'Name',
                start: 76,
                end: 86,
                line: 4,
                column: 5,
                value: 'adminNotes',
                prev: "[Circular]",
                next: {
                  kind: '}',
                  start: 89,
                  end: 90,
                  line: 5,
                  column: 3,
                  value: undefined,
                  prev: "[Circular]",
                  next: {
                    kind: '}',
                    start: 91,
                    end: 92,
                    line: 6,
                    column: 1,
                    value: undefined,
                    prev: "[Circular]",
                    next: {
                      kind: '<EOF>',
                      start: 93,
                      end: 93,
                      line: 7,
                      column: 1,
                      value: undefined,
                      prev: "[Circular]",
                      next: null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    endToken: {
      kind: 'String',
      start: 22,
      end: 60,
      line: 2,
      column: 21,
      value: 'ffcafdc2-2080-4721-b560-bbd7665b805c',
      prev: {
        kind: ':',
        start: 20,
        end: 21,
        line: 2,
        column: 19,
        value: undefined,
        prev: {
          kind: 'Name',
          start: 18,
          end: 20,
          line: 2,
          column: 17,
          value: 'id',
          prev: {
            kind: '{',
            start: 17,
            end: 18,
            line: 2,
            column: 16,
            value: undefined,
            prev: {
              kind: ':',
              start: 15,
              end: 16,
              line: 2,
              column: 14,
              value: undefined,
              prev: {
                kind: 'Name',
                start: 10,
                end: 15,
                line: 2,
                column: 9,
                value: 'where',
                prev: {
                  kind: '(',
                  start: 9,
                  end: 10,
                  line: 2,
                  column: 8,
                  value: undefined,
                  prev: {
                    kind: 'Name',
                    start: 4,
                    end: 9,
                    line: 2,
                    column: 3,
                    value: 'order',
                    prev: {
                      kind: '{',
                      start: 0,
                      end: 1,
                      line: 1,
                      column: 1,
                      value: undefined,
                      prev: {
                        kind: '<SOF>',
                        start: 0,
                        end: 0,
                        line: 0,
                        column: 0,
                        value: undefined,
                        prev: null,
                        next: "[Circular]"
                      },
                      next: "[Circular]"
                    },
                    next: "[Circular]"
                  },
                  next: "[Circular]"
                },
                next: "[Circular]"
              },
              next: "[Circular]"
            },
            next: "[Circular]"
          },
          next: "[Circular]"
        },
        next: "[Circular]"
      },
      next: {
        kind: '}',
        start: 60,
        end: 61,
        line: 2,
        column: 59,
        value: undefined,
        prev: "[Circular]",
        next: {
          kind: ')',
          start: 61,
          end: 62,
          line: 2,
          column: 60,
          value: undefined,
          prev: "[Circular]",
          next: {
            kind: '{',
            start: 63,
            end: 64,
            line: 2,
            column: 62,
            value: undefined,
            prev: "[Circular]",
            next: {
              kind: 'Name',
              start: 69,
              end: 71,
              line: 3,
              column: 5,
              value: 'id',
              prev: "[Circular]",
              next: {
                kind: 'Name',
                start: 76,
                end: 86,
                line: 4,
                column: 5,
                value: 'adminNotes',
                prev: "[Circular]",
                next: {
                  kind: '}',
                  start: 89,
                  end: 90,
                  line: 5,
                  column: 3,
                  value: undefined,
                  prev: "[Circular]",
                  next: {
                    kind: '}',
                    start: 91,
                    end: 92,
                    line: 6,
                    column: 1,
                    value: undefined,
                    prev: "[Circular]",
                    next: {
                      kind: '<EOF>',
                      start: 93,
                      end: 93,
                      line: 7,
                      column: 1,
                      value: undefined,
                      prev: "[Circular]",
                      next: null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    source: {
      body: '{\n  order(where: {id: "ffcafdc2-2080-4721-b560-bbd7665b805c"}) {\n    id\n    adminNotes\n  }\n}\n',
      name: 'GraphQL request',
      locationOffset: {
        line: 1,
        column: 1
      }
    }
  }
}
on photon.findOneOrder. Provided Json, expected UUID.


    at Document.validate (/Users/zane/repos/project/packages/prisma/node_modules/@generated/photon/runtime/index.js:1744:23)
    at OrderClient.get _document [as _document] (/Users/zane/repos/project/packages/prisma/node_modules/@generated/photon/index.js:1696:22)
    at OrderClient.then (/Users/zane/repos/project/packages/prisma/node_modules/@generated/photon/index.js:1717:63)
    at whenResultIsFinished (/Users/zane/repos/project/node_modules/graphql-extensions/src/index.ts:171:12)
    at field.resolve (/Users/zane/repos/project/node_modules/graphql-extensions/src/index.ts:156:7)
    at resolveFieldValueOrError (/Users/zane/repos/project/node_modules/graphql/execution/execute.js:544:18)
    at resolveField (/Users/zane/repos/project/node_modules/graphql/execution/execute.js:508:16)
    at /Users/zane/repos/project/node_modules/graphql/execution/execute.js:357:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/zane/repos/project/node_modules/graphql/execution/execute.js:354:42)
```

</details>
