### ISSUE TITLE
Error while using `@relation` on a schema  

### ISSUE THREAD

**Issue by Katolus** [prisma/prisma2#848]
Getting below error while running `@relation` (unavailable feature) on a schema. I had to delete delete `dev/` migrations and kills the process manually in order to run `prisma2 dev` correctly again.
```
Error: Error: ETXTBSY: text file is busy, copyfile '/home/katolus/personal/book-service/node_modules/pri
sma2/build/query-engine-linux-glibc-libssl1.1.0' -> '/home/katolus/personal/book-service/node_modules/@g
enerated/photon/runtime/query-engine-linux-glibc-libssl1.1.0'
    at GeneratorProcess.handleResponse (/home/katolus/personal/book-service/node_modules/prisma2/build/i
ndex.js:477448:35)
    at LineStream.byline_1.default.on.line (/home/katolus/personal/book-service/node_modules/prisma2/bui
ld/index.js:477426:26)
    at LineStream.emit (events.js:189:13)
    at LineStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at LineStream.Readable.push (_stream_readable.js:220:10)
    at LineStream.Transform.push (_stream_transform.js:151:32)
    at LineStream.module.exports.LineStream._pushBuffer (/home/katolus/personal/book-service/node_module
s/prisma2/build/index.js:598578:23)
    at LineStream.module.exports.LineStream._transform (/home/katolus/personal/book-service/node_modules
/prisma2/build/index.js:598570:10)
```

If a feature is not existing, what is the point of putting in the docs?
https://github.com/prisma/prisma2/blob/master/docs/relations.md#the-relation-attribute

**Comment by pantharshit00** [comment]
`@relation` is not an unavailable feature. Can you please provide me with the exact steps to reproduce this problem?

**Comment by divyenduz** [comment]
@Katolus  I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
