### ISSUE TITLE
prisma init fails on seeding Postgre

### ISSUE THREAD

**Issue by capaj** [prisma/prisma2#901]
This is my output:

```
prisma2 init mvp

Preparing your starter kit: GraphQL API (+ Auth)

✔  Downloading the starter kit from GitHub ...
⠙  Extracting content to mvp ...
3  Installing dependencies with: `npm install` ...
4  Preparing your database ...
5  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

DMMF To DML thread 'main' panicked at 'File should open read only: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:116
5:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88

Preparing your starter kit: GraphQL API (+ Auth)

✔  Downloading the starter kit from GitHub ...
⠙  Extracting content to mvp ...
3  Installing dependencies with: `npm install` ...
4  Preparing your database ...
5  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

DMMF To DML thread 'main' panicked at 'File should open read only: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:116
5:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: prisma::cli::CliCommand::new
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
  17: tokio_executor::enter::Enter::block_on
  18: tracing_core::dispatcher::with_default
  19: std::thread::local::LocalKey<T>::with
  20: tokio::runtime::threadpool::Runtime::block_on
  21: prisma::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  26: std::panicking::try
             at src/libstd/panicking.rs:271
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
I am on ubuntu 19.10

**Comment by ErickGomez98** [comment]
I'm having the same issue on windows with prisma2@2.0.0-preview016

**Comment by pantharshit00** [comment]
@capaj 

Thanks for opening this. I didn't get to this one and opened a new issue for this problem which has more context now. So I am going to close this in favour of https://github.com/prisma/prisma2/issues/904
