### ISSUE TITLE
Encountering an error in Prisma Studio after running "prisma2 dev"

### ISSUE THREAD

**Issue by jwld** [prisma/prisma2#949]
Datamodel:
```
generator photon {
  provider = "photonjs"
}

model Expansion {
  levelMin  Int
  name      String
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id @unique
  updatedAt DateTime @updatedAt
}

model Mount {
  expansion Expansion
  name      String
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id @unique
  updatedAt DateTime @updatedAt
}
```

Error:
```
Error in Photon: 
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyMount", inner: ObjectValidationError { object_name: "Mount", inner: FieldValidationError { field_name: "expansion", inner: FieldNotFoundError } } } })

    at NodeEngine.handleErrors (/usr/local/lib/node_modules/prisma2/build/index.js:338814:15)
    at /usr/local/lib/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/69036777-8c6c1400-0a0c-11ea-896b-3fe00637235c.png)


Can you please try clearing the site data using devtools and trying again?
