### ISSUE TITLE
Prisma Studio : "Failed to run script"

### ISSUE THREAD

**Issue by HubnerJonathan** [prisma/prisma2#951]
Hi,

I'm new to the prisma framework. When I try to use prisma studio (by default on http://localhost:5555/) this error appears. I can still use studio and navigate into the different tables of my DB but they appear empty.

`Error in Photon: 
Error: undefined target="exit" timestamp="2019-11-18T15:40:41.176Z" fields={"message":"255"}
    at /home/avalon/.nvm/versions/node/v12.2.0/lib/node_modules/prisma2/build/index.js:338787:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)`

I'm using Ubuntu 18.04.3.

BR,

**Comment by pantharshit00** [comment]
Hi,

Are you using Prisma over an existing database or it is a new database? Also, are you able to read data programmatically using photon?

You can also try clearing the site data in chrome dev tools and trying this again.

Also, please provide the output of `lsb_release -a`, `uname -a` and `openssl version` so that we can know more about your OS.

**Comment by HubnerJonathan** [comment]
Hi,

The database was created with `prisma2 init` in Sqlite. I can read data using photon and my resolvers works just fine when I hit the DB trough the prisma server. Clearing the website data does not change anything.

**lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**uname -a**
Linux avalon-home 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**openssl version**
OpenSSL 1.1.1  11 Sep 2018

In the console of studio i got a lot of errors : 

- `studioBundle.js:102 Uncaught (in promise) DOMException: Connection is closing.`

- `Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (http://localhost:5555/studioBundle.js:102:9807)
    at Proxy.r (http://localhost:5555/studioBundle.js:102:11297)
    at http://localhost:5555/studioBundle.js:102:11952`
- `POST https://sentry.io/api/1762788/store/?sentry_key=fb6e137ff2ea425da39d6e92a4d69b58&sentry_version=7 429 (Too Many Requests)`

**Comment by malekjaroslav** [comment]
I get this error now 

> Hi,
> 
> I'm new to the prisma framework. When I try to use prisma studio (by default on http://localhost:5555/) this error appears. I can still use studio and navigate into the different tables of my DB but they appear empty.
> 
> `Error in Photon: Error: undefined target="exit" timestamp="2019-11-18T15:40:41.176Z" fields={"message":"255"} at /home/avalon/.nvm/versions/node/v12.2.0/lib/node_modules/prisma2/build/index.js:338787:27 at processTicksAndRejections (internal/process/task_queues.js:89:5)`
> 
> I'm using Ubuntu 18.04.3.
> 
> BR,

@pantharshit00 I get this error now as well running on Cloud Run (not from Studio, but Photon). When I restart the "server" it starts working again. As there is no specific error it is hard to say where it comes from.
